//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface NTLocalizedString : NSObject
{
}

+ (id)localize:(id)arg1;
+ (id)localize:(id)arg1 table:(id)arg2;
+ (void)localizeWindow:(id)arg1;
+ (void)localizeWindow:(id)arg1 table:(id)arg2;
+ (void)localizeView:(id)arg1;
+ (void)localizeView:(id)arg1 table:(id)arg2;

@end

