//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTFileDesc;

@interface CalcSizeToken : NSObject
{
    NTFileDesc *_desc;
    id _itemIdentifier;
}

+ (id)calcSizeForDesc:(id)arg1 withItemIdentifier:(id)arg2;
- (id)initWithDesc:(id)arg1 withItemIdentifier:(id)arg2;
- (void)dealloc;
- (id)itemIdentifier;
- (id)desc;

@end

