//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface CalcSizeResult : NSObject
{
    NSNumber *_size;
    NSNumber *_numItems;
    BOOL _numItemsValid;
}

+ (id)resultWithSize:(id)arg1 numItems:(id)arg2 numItemsValid:(BOOL)arg3;
- (id)initWithSize:(id)arg1 numItems:(id)arg2 numItemsValid:(BOOL)arg3;
- (void)dealloc;
- (id)size;
- (id)numItems;
- (BOOL)isNumItemsValid;

@end

