//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Function Pointers

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct AEDesc {
    unsigned int _field1;
    struct OpaqueAEDataStorageType **_field2;
};

struct FSAliasInfo {
    struct UTCDateTime volumeCreateDate;
    struct UTCDateTime targetCreateDate;
    unsigned int fileType;
    unsigned int fileCreator;
    unsigned int parentDirID;
    unsigned int nodeID;
    unsigned short filesystemID;
    unsigned short signature;
    unsigned char volumeIsBootVolume;
    unsigned char volumeIsAutomounted;
    unsigned char volumeIsEjectable;
    unsigned char volumeHasPersistentFileIDs;
    unsigned char isDirectory;
};

struct FSCatalogInfo {
    unsigned short nodeFlags;
    short volume;
    unsigned int parentDirID;
    unsigned int nodeID;
    unsigned char sharingFlags;
    unsigned char userPrivileges;
    unsigned char reserved1;
    unsigned char reserved2;
    struct UTCDateTime createDate;
    struct UTCDateTime contentModDate;
    struct UTCDateTime attributeModDate;
    struct UTCDateTime accessDate;
    struct UTCDateTime backupDate;
    unsigned int permissions[4];
    unsigned char finderInfo[16];
    unsigned char extFinderInfo[16];
    unsigned long long dataLogicalSize;
    unsigned long long dataPhysicalSize;
    unsigned long long rsrcLogicalSize;
    unsigned long long rsrcPhysicalSize;
    unsigned int valence;
    unsigned int textEncodingHint;
};

struct FSRef {
    unsigned char hidden[80];
};

struct FSSpec {
    short _field1;
    long _field2;
    unsigned char _field3[64];
};

struct FSVolumeInfo {
    struct UTCDateTime createDate;
    struct UTCDateTime modifyDate;
    struct UTCDateTime backupDate;
    struct UTCDateTime checkedDate;
    unsigned int fileCount;
    unsigned int folderCount;
    unsigned long long totalBytes;
    unsigned long long freeBytes;
    unsigned int blockSize;
    unsigned int totalBlocks;
    unsigned int freeBlocks;
    unsigned int nextAllocation;
    unsigned int rsrcClumpSize;
    unsigned int dataClumpSize;
    unsigned int nextCatalogID;
    unsigned char finderInfo[32];
    unsigned short flags;
    unsigned short filesystemID;
    unsigned short signature;
    unsigned short driveNumber;
    short driverRefNum;
};

struct FileInfo {
    unsigned int fileType;
    unsigned int fileCreator;
    unsigned short finderFlags;
    struct Point location;
    unsigned short reservedField;
};

struct ForkTracker {
    struct HFSUniStr255 _field1;
    long long _field2;
    short _field3;
};

struct GetVolParmsInfoBuffer {
    short vMVersion;
    long vMAttrib;
    char **vMLocalHand;
    long vMServerAdr;
    long vMVolumeGrade;
    short vMForeignPrivID;
    long vMExtendedAttributes;
    void *vMDeviceID;
    unsigned int vMMaxNameLength;
};

struct HFSUniStr255 {
    unsigned short _field1;
    unsigned short _field2[255];
};

struct LSItemInfoRecord {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int _field3;
    struct __CFString *_field4;
    struct __CFString *_field5;
    unsigned int _field6;
};

struct OpaqueAEDataStorageType;

struct OpaqueFNSubscriptionRef {
    unsigned int _field1;
    CDUnknownFunctionPointerType _field2;
    void *_field3;
    struct FSRef _field4;
    struct __CFString *_field5;
};

struct Point {
    short v;
    short h;
};

struct ProcessSerialNumber {
    unsigned int highLongOfPSN;
    unsigned int lowLongOfPSN;
};

struct RGBColor {
    unsigned short red;
    unsigned short green;
    unsigned short blue;
};

struct UTCDateTime {
    unsigned short highSeconds;
    unsigned int lowSeconds;
    unsigned short fraction;
};

struct _NSPoint {
    float x;
    float y;
};

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct _NSRect {
    struct _NSPoint origin;
    struct _NSSize size;
};

struct _NSSize {
    float width;
    float height;
};

struct __CFString;

struct fsid {
    int val[2];
};

struct statfs {
    short f_otype;
    short f_oflags;
    long f_bsize;
    long f_iosize;
    long f_blocks;
    long f_bfree;
    long f_bavail;
    long f_files;
    long f_ffree;
    struct fsid f_fsid;
    unsigned int f_owner;
    short f_reserved1;
    short f_type;
    long f_flags;
    long f_reserved2[2];
    char f_fstypename[15];
    char f_mntonname[90];
    char f_mntfromname[90];
    char f_reserved3;
    long f_reserved4[4];
};

struct timespec {
    int _field1;
    long _field2;
};

