//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface HiddenFileList : NSObject
{
    short _volumeRefNum;
    NSSet *_hiddenFileSet;
}

+ (id)listWithVolumeRefNum:(short)arg1;
- (id)initWithVolumeRefNum:(short)arg1;
- (short)volumeRefNum;
- (BOOL)isHidden:(id)arg1;
- (void)dealloc;

@end

