//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor, NSString;

@interface LabelColor : NSObject
{
    NSColor *_color;
    struct RGBColor _rgbColor;
    NSString *_label;
}

- (void)dealloc;
- (id)initWithLabel:(id)arg1 color:(id)arg2 rgbColor:(struct RGBColor *)arg3;
- (id)color;
- (struct RGBColor *)rgbColor;
- (id)label;

@end

