//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NameAndID : NSObject
{
    int _ident;
    NSString *_name;
}

+ (id)nameAndID:(id)arg1 ident:(int)arg2;
- (id)initWithName:(id)arg1 ident:(int)arg2;
- (void)dealloc;
- (int)ident;
- (id)name;

@end

