//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTAliasFileManager : NSObject
{
}

+ (id)resolveAliasFile:(id)arg1 resolveServer:(BOOL)arg2 outIsServerAlias:(char *)arg3;
+ (id)createAliasFile:(id)arg1 atPath:(id)arg2;
+ (id)createPathFinderAliasFile:(id)arg1 atPath:(id)arg2;
+ (id)resolvePathFinderAliasFile:(id)arg1 resolveServer:(BOOL)arg2 outIsServerAlias:(char *)arg3;

@end

