//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSData, NSString, NTFileDesc;

@interface NTAlias : NSObject <NSCoding>
{
    NTFileDesc *_desc;
    NSData *_alias;
    struct AliasRecord **_aliasHandle;
    BOOL _gotAliasInfo;
    unsigned int _whichAliasInfo;
    struct FSAliasInfo _aliasInfo;
    NSString *_path;
    NSString *_targetName;
    NSString *_volumeName;
    BOOL _aliasRequiresUIToResolve;
    unsigned int _userType;
    unsigned short _aliasSize;
    unsigned int _aliasType;
}

+ (id)aliasWithDesc:(id)arg1;
+ (id)aliasWithAlias:(id)arg1;
+ (id)aliasWithAliasFile:(id)arg1;
- (void)commonInit;
- (id)initWithDesc:(id)arg1;
- (id)initWithAliasFile:(id)arg1;
- (id)initWithAlias:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)desc;
- (id)desc:(BOOL)arg1;
- (id)alias;
- (unsigned long)aliasType;
- (BOOL)aliasRequiresUIToResolve;
- (unsigned long)userType;
- (id)path;
- (id)targetName;
- (id)volumeName;
- (struct FSAliasInfo *)aliasInfo;
- (unsigned long)whichAliasInfo;
- (id)volumeCreationDate;
- (id)targetCreationDate;
- (unsigned long)fileType;
- (unsigned long)fileCreator;
- (unsigned long)parentDirID;
- (unsigned long)nodeID;
- (unsigned short)filesystemID;
- (unsigned short)signature;
- (BOOL)volumeIsBootVolume;
- (BOOL)volumeIsAutomounted;
- (BOOL)volumeIsEjectable;
- (BOOL)volumeHasPersistentFileIDs;
- (BOOL)isDirectory;

@end

