//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTAlias.h>

@interface NTAlias (Private)
- (void)initDesc:(BOOL)arg1;
- (void)initAlias;
- (struct AliasRecord **)aliasHandle;
- (void)getAliasInfo;
- (void)setAlias:(id)arg1;
@end

