//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTAlias.h>

@interface NTAlias (Utilities)
+ (id)resolveAlias:(struct AliasRecord **)arg1 resolveIfRequiresUI:(BOOL)arg2 outAliasRequiresUIToResolve:(char *)arg3 outWasChanged:(char *)arg4;
+ (struct AliasRecord **)aliasHandleForDesc:(id)arg1;
+ (id)handleToData:(char **)arg1;
+ (char **)dataToHandle:(id)arg1;
+ (unsigned long)fileTypeForAliasFileOfDesc:(id)arg1;
@end

