//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NTFileDesc;

@interface NTApplicationLocator : NSObject
{
    NTFileDesc *_desc;
    NSMutableSet *_visitedFolders;
    int _maximumSearchLevel;
}

- (id)initWithDesc:(id)arg1;
- (void)dealloc;
- (id)findApplications:(int)arg1;

@end

