//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTApplicationLocator.h>

@interface NTApplicationLocator (Private)
- (BOOL)shouldSearchDesc:(id)arg1;
- (id)recursiveFindApplications:(id)arg1 level:(int)arg2;
@end

