//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTChooseDestinationPanel : NSObject
{
    NSString *_path;
    id _contextInfo;
    BOOL _userClickedOK;
    SEL _selector;
    id _target;
}

+ (void)chooseDestination:(id)arg1 window:(id)arg2 target:(id)arg3 selector:(SEL)arg4 contextInfo:(id)arg5;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 contextInfo:(id)arg3;
- (void)dealloc;
- (void)openPanelDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (BOOL)userClickedOK;
- (id)path;
- (id)contextInfo;

@end

