//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTCopyProgress;

@interface NTCopyEngine : NSObject
{
    void *_copyBuffer;
    unsigned int _copyBufferSize;
    unsigned char _copyingToDropFolder;
    unsigned char _srcIsLocalVolume;
    unsigned char _destIsLocalVolume;
    unsigned char _copyUsingPBHCopyFile;
    unsigned char _copyNamedForks;
    short _srcVRefNum;
    struct GetVolParmsInfoBuffer _srcVolParms;
    short _destVRefNum;
    struct GetVolParmsInfoBuffer _destVolParms;
    NTCopyProgress *_progress;
    unsigned long long _numFilesCopied;
    unsigned long long _numFoldersCreated;
}

+ (id)engineWithProgress:(id)arg1;
- (id)initWithProgress:(id)arg1;
- (void)dealloc;
- (BOOL)requestCanceled;
- (short)copyObject:(const struct FSRef *)arg1 destDir:(const struct FSRef *)arg2 newName:(id)arg3;
- (short)deleteObjects:(const struct FSRef *)arg1;
- (unsigned long long)numFilesCopied;
- (unsigned long long)numFoldersCreated;

@end

