//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTCopyProgress : NSObject
{
    id _delegate;
    BOOL _sendProgress;
    BOOL _sendPrepProgress;
    BOOL _sendErrors;
    BOOL _requestCanceled;
    unsigned long long _numBytes;
    unsigned long long _bytesCopied;
    unsigned int _numItemsToCopy;
    unsigned int _numItemsCopied;
}

+ (id)progressWithDelegate:(id)arg1;
- (id)initWithDelegate:(id)arg1;
- (void)dealloc;
- (void)setNumItemsToCopy:(unsigned long)arg1;
- (void)setNumBytesToCopy:(unsigned long long)arg1;
- (void)incrementNumItemsCopied:(unsigned long)arg1;
- (void)incrementBytesCopied:(unsigned long)arg1;
- (void)sendErrorToDelegate:(id)arg1 error:(id)arg2;
- (void)sendPrepareProgressToDelegate:(id)arg1 itemsProcessed:(unsigned long)arg2;
- (void)sendCopyProgressToDelegate:(id)arg1;
- (void)setRequestCanceled:(BOOL)arg1;
- (BOOL)requestCanceled;

@end

