//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTContextualMenuHandler : NSObject
{
}

+ (id)sharedInstance;
- (void)popUpContextMenu:(id)arg1 withEvent:(id)arg2 forView:(id)arg3;
- (void)popUpContextMenuWithFinderCMs:(id)arg1 withEvent:(id)arg2 forView:(id)arg3 selection:(id)arg4;

@end

