//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTCopyEngine.h>

@interface NTCopyEngine (Private)
- (BOOL)initCopyParams:(const struct FSRef *)arg1 dest:(const struct FSRef *)arg2;
- (short)FSCopyFile:(const struct FSRef *)arg1 destDir:(const struct FSRef *)arg2 newName:(id)arg3;
- (short)CopyFile:(const struct FSRef *)arg1 sourceCatInfo:(struct FSCatalogInfo *)arg2 destDir:(const struct FSRef *)arg3 destName:(const struct HFSUniStr255 *)arg4;
- (short)FSUsePBHCopyFile:(const struct FSRef *)arg1 dstDirectoryRef:(const struct FSRef *)arg2 nameLength:(unsigned long)arg3 copyName:(const unsigned short *)arg4 textEncodingHint:(unsigned long)arg5;
- (short)DoCopyFile:(const struct FSRef *)arg1 sourceCatInfo:(struct FSCatalogInfo *)arg2 destDir:(const struct FSRef *)arg3 destName:(const struct HFSUniStr255 *)arg4;
- (short)FSCopyFolder:(const struct FSRef *)arg1 destDir:(const struct FSRef *)arg2 newName:(id)arg3;
- (short)FSCopyFolderLevel:(const struct FSRef *)arg1 sourceCatInfo:(struct FSCatalogInfo *)arg2 destDir:(const struct FSRef *)arg3 destName:(const struct HFSUniStr255 *)arg4;
- (short)CheckForDestInsideSource:(const struct FSRef *)arg1 destDir:(const struct FSRef *)arg2;
- (short)CopyItemsForks:(const struct FSRef *)arg1 sourceCatInfo:(struct FSCatalogInfo *)arg2 dest:(const struct FSRef *)arg3 destName:(const struct HFSUniStr255 *)arg4;
- (short)OpenAllForks:(const struct FSRef *)arg1 dataFork:(struct ForkTracker *)arg2 rsrcFork:(struct ForkTracker *)arg3 otherForks:(struct ForkTracker *)arg4 otherForksCount:(unsigned long)arg5;
- (short)CopyFork:(const struct FSRef *)arg1 dest:(const struct FSRef *)arg2 destName:(const struct HFSUniStr255 *)arg3 sourceFork:(struct ForkTracker *)arg4;
- (short)CloseAllForks:(short)arg1 rsrcRefNum:(short)arg2 otherForks:(struct ForkTracker *)arg3 otherForksCount:(unsigned long)arg4;
- (short)CalculateForksToCopy:(const struct FSRef *)arg1 dataFork:(struct ForkTracker *)arg2 rsrcFork:(struct ForkTracker *)arg3 copyNamedForks:(BOOL)arg4 otherForks:(struct ForkTracker **)arg5 otherForksCount:(unsigned int *)arg6;
- (unsigned long)BufferSizeForThisVolume:(struct GetVolParmsInfoBuffer *)arg1;
- (unsigned long)BufferSizeForThisVolumeSpeed:(unsigned long)arg1;
- (short)FSDeleteFolder:(const struct FSRef *)arg1;
- (short)FSDeleteFolderLevel:(const struct FSRef *)arg1;
- (short)IsDropBox:(const struct FSRef *)arg1 isDropBox:(char *)arg2;
- (unsigned char)CompareHFSUniStr255:(const struct HFSUniStr255 *)arg1 rhs:(const struct HFSUniStr255 *)arg2;
- (short)FSGetVRefNum:(const struct FSRef *)arg1 vRefNum:(short *)arg2;
- (short)FSGetVolParms:(short)arg1 bufferSize:(unsigned long)arg2 volParmsInfo:(struct GetVolParmsInfoBuffer *)arg3 actualInfoSize:(unsigned int *)arg4;
- (short)UnicodeNameGetHFSName:(unsigned long)arg1 name:(const unsigned short *)arg2 textEncodingHint:(unsigned long)arg3 hfsName:(char *)arg4 maxLength:(int)arg5;
- (short)FSMakeFSRef:(short)arg1 dirID:(long)arg2 name:(char *)arg3 ref:(struct FSRef *)arg4;
- (struct UTCDateTime *)magicBusyCreateDate;
- (void)reportErrorToUser:(short)arg1 item:(const struct FSRef *)arg2;
@end

