//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSString;

@interface NTDefaultDirectory : NSObject
{
    NSString *_homePath;
    NSString *_favoritesPath;
    NSString *_trashPath;
    NSString *_userLibraryPath;
    NSString *_userContextualMenuItemsPath;
    NSString *_userApplicationsPath;
    NSString *_desktopPath;
    NSString *_documentsPath;
    NSString *_musicPath;
    NSString *_moviesPath;
    NSString *_picturesPath;
    NSString *_sitesPath;
    NSString *_publicPath;
    NSString *_userApplicationSupportPath;
    NSString *_userApplicationSupportApplicationPath;
    NSString *_userApplicationSupportPluginsPath;
    NSString *_applicationSupportPath;
    NSString *_applicationSupportApplicationPath;
    NSString *_applicationSupportPluginsPath;
    NSString *_userPreferencesPath;
    NSString *_computerPath;
    NSString *_rootPath;
    NSString *_systemPath;
    NSString *_usersPath;
    NSString *_libraryPath;
    NSString *_applicationsPath;
    NSString *_classicApplicationsPath;
    NSString *_developerApplicationsPath;
    NSString *_networkApplicationsPath;
    NSString *_tmpPath;
    NSString *_contextualMenuItemsPath;
    NSString *_recentServersPath;
    NSString *_networkPath;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)homePath;
- (id)favoritesPath;
- (id)trashPath;
- (id)trashPathForDesc:(id)arg1;
- (id)userLibraryPath;
- (id)userContextualMenuItemsPath;
- (id)contextualMenuItemsPath;
- (id)userApplicationsPath;
- (id)desktopPath;
- (id)documentsPath;
- (id)musicPath;
- (id)moviesPath;
- (id)picturesPath;
- (id)sitesPath;
- (id)publicPath;
- (id)recentServersPath;
- (id)computerPath;
- (id)networkPath;
- (id)rootPath;
- (id)systemPath;
- (id)usersPath;
- (id)libraryPath;
- (id)applicationsPath;
- (id)classicApplicationsPath;
- (id)developerApplicationsPath;
- (id)networkApplicationsPath;
- (id)tmpPath;
- (id)userApplicationSupportPath;
- (id)userApplicationSupportApplicationPath;
- (id)applicationSupportPath;
- (id)applicationSupportApplicationPath;
- (id)userPreferencesPath;
- (id)userApplicationSupportPluginsPath;
- (id)applicationSupportPluginsPath;
- (id)favorites;
- (id)userLibrary;
- (id)contextualMenuItems;
- (id)userContextualMenuItems;
- (id)trash;
- (id)root;
- (id)library;
- (id)users;
- (id)system;
- (id)home;
- (id)applications;
- (id)network;
- (id)classicApplications;
- (id)developerApplications;
- (id)networkApplications;
- (id)userApplications;
- (id)desktop;
- (id)documents;
- (id)music;
- (id)movies;
- (id)pictures;
- (id)sites;
- (id)public;
- (id)recentServers;
- (id)computer;
- (id)tmp;
- (id)userApplicationSupport;
- (id)userApplicationSupportApplication;
- (id)userApplicationSupportPlugins;
- (id)applicationSupport;
- (id)applicationSupportApplication;
- (id)applicationSupportPlugins;
- (id)userPreferences;
- (id)trashForDesc:(id)arg1;
- (BOOL)makeTrash;
- (BOOL)makeTrashAtDesc:(id)arg1;

@end

