//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface NTDirectoryWatcher : NSObject
{
    NSMutableArray *_directories;
    SEL _sel;
    id _target;
}

+ (id)watcher:(id)arg1 selector:(SEL)arg2;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2;
- (void)dealloc;
- (id)directories;
- (void)addDirectory:(id)arg1;
- (void)addDirectories:(id)arg1;
- (void)removeDirectory:(id)arg1;
- (void)removeDirectories:(id)arg1;
- (void)removeAll;
- (void)replaceDirectories:(id)arg1;

@end

