//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTDiskUtilTask.h>

@interface NTDiskUtilTask (Private)
- (void)renameDisk:(id)arg1 atMountPoint:(id)arg2;
- (void)disposeTask;
@end

