//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTDirectoryDefaults.h>

@interface NTDirectoryDefaults (Private)
- (void)saveToFile;
- (void)loadFromFile;
- (id)pathToPreferencesFolder;
- (id)pathToFile;
- (BOOL)fileExists;
@end

