//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTDirectoryWatcher.h>

@interface NTDirectoryWatcher (Private)
- (void)removeFromDirectoriesArray:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addNotificationObserver:(id)arg1;
- (void)removeNotificationObserver:(id)arg1;
- (void)directoryModifiedNotification:(id)arg1;
@end

