//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NTSimpleTimerProtocol.h"

@class NSMutableDictionary, NTSimpleTimer;

@interface NTDirectoryDefaultsMgr : NSObject <NTSimpleTimerProtocol>
{
    NTSimpleTimer *_timer;
    BOOL _needsToSyncWithFile;
    NSMutableDictionary *_directoryDefaults;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)objectForKey:(id)arg1 directory:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2 directory:(id)arg3;
- (struct _NSPoint)iconPositionForDesc:(id)arg1;
- (void)setIconPosition:(struct _NSPoint)arg1 forDesc:(id)arg2;
- (void)delegate_simpleTimerNotification:(id)arg1;

@end

