//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface NTDirectoryWatcherMgr : NSObject
{
    NSMutableArray *_observers;
    CDUnknownFunctionPointerType _procUPP;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)addObserver:(id)arg1;
- (void)removeObserver:(id)arg1;

@end

