//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTDirectoryDefaultsMgr.h>

@interface NTDirectoryDefaultsMgr (Private)
- (void)syncWithFiles;
- (id)keyForDirectory:(id)arg1;
- (id)defaultsForDirectory:(id)arg1;
- (BOOL)isSpecialDirectory:(id)arg1;
@end

