//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTDragDropUtils : NSObject
{
}

+ (unsigned int)decodeDragFlags:(unsigned int)arg1;
+ (void)doAcceptURLDrop:(id)arg1 iconPosition:(id)arg2 inDirectory:(id)arg3;
+ (void)doAcceptTextDrop:(id)arg1 iconPosition:(id)arg2 inDirectory:(id)arg3;
+ (void)dragDragDropIndicatorInRect:(struct _NSRect)arg1 selected:(BOOL)arg2;
+ (void)writePaths:(id)arg1 toPasteboard:(id)arg2;

@end

