//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface NTDragInfo : NSObject
{
    int _sequenceNumber;
    BOOL _hasTextData;
    BOOL _hasRTFTextData;
    BOOL _hasRTFDTextData;
    BOOL _hasFileData;
    BOOL _hasFilePromiseData;
    BOOL _hasURLData;
    NSArray *_descs;
    NSArray *_paths;
    BOOL _dragHasVolume;
    int _volumeRefNumForFiles;
    int _filesOnMultipleVolumes;
    unsigned int _defaultDragOperation;
}

+ (id)dragInfo:(id)arg1;
- (id)initWithInfo:(id)arg1;
- (int)sequenceNumber;
- (void)setDefaultDragOperation:(unsigned int)arg1;
- (BOOL)hasTextData;
- (BOOL)hasRTFTextData;
- (BOOL)hasFileData;
- (BOOL)hasFilePromiseData;
- (BOOL)hasURLData;
- (id)urlTitle:(id)arg1;
- (id)urlString:(id)arg1;
- (id)descs;
- (id)paths;
- (BOOL)dragHasVolume;
- (id)textData:(id)arg1;
- (id)rtfData:(id)arg1;
- (unsigned int)dragOperation:(id)arg1 forDestination:(id)arg2;
- (int)fileAction:(id)arg1 forDestination:(id)arg2;

@end

