//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFileActionRequest.h>

@interface NTFileActionRequest (Private)
- (BOOL)preflightCheckMakeAlias;
- (BOOL)preflightCheckModifyFiles;
- (BOOL)preflightCheckDeleteFiles;
- (BOOL)preflightCheckCopy;
- (BOOL)preflightCheckMove;
- (BOOL)isSrcItemsMovable;
- (BOOL)isSrcItemsOK;
- (BOOL)isDestFolderOK;
- (BOOL)isDestInsideTheSrcDirectory;
- (BOOL)isSrcAndDestOnSameVolume;
- (BOOL)isFileReplaceOK;
- (BOOL)isSourceAndDestAreSame;
- (BOOL)isDestTheParentOfSrc;
- (void)addDestPath:(id)arg1 destName:(id)arg2;
- (BOOL)nameExistsInDestPaths:(id)arg1;
- (void)addItem:(id)arg1;
- (void)addItem:(id)arg1 withName:(id)arg2;
- (void)removeItem:(int)arg1;
- (void)removeItemsWithParentInList;
@end

