//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTFileDescMem : NSObject
{
    unsigned int _capacity;
    struct FSRef *_refArray;
    struct FSCatalogInfo *_catalogInfoArray;
    struct HFSUniStr255 *_nameArray;
}

+ (id)cacheWithCapacity:(unsigned int)arg1;
- (id)initWithCapacity:(unsigned int)arg1;
- (void)dealloc;
- (unsigned int)capacity;
- (unsigned int)minimumCapacity;
- (struct FSRef *)refArray;
- (struct FSCatalogInfo *)catalogInfoArray;
- (struct HFSUniStr255 *)nameArray;

@end

