//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFileDeleter.h>

@interface NTFileDeleter (Private)
- (BOOL)doDeleteFile:(id)arg1;
- (BOOL)doDeleteDirectory:(id)arg1;
- (void)setWritePermissions:(id)arg1;
- (void)unlockDesc:(id)arg1;
@end

