//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTFileActionRequest;

@interface NTFileRequestProcessor : NSObject
{
    BOOL _sendProgress;
    BOOL _sendPrepProgress;
    BOOL _sendErrors;
    id _delegate;
    NTFileActionRequest *_actionRequest;
    BOOL _requestCanceled;
    unsigned long long _numBytes;
    unsigned int _numItemsToCopy;
    BOOL _didProcessEveryFile;
}

- (id)initWithDelegate:(id)arg1;
- (void)dealloc;
- (BOOL)didProcessEveryFile;
- (BOOL)processRequest:(id)arg1;

@end

