//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface NTFileUtilities : NSObject
{
}

+ (id)setAttributesToReadWrite:(id)arg1;
+ (int)findMatchingDirectory:(id)arg1 outPath:(id *)arg2 visibleOnly:(BOOL)arg3 treatPackagesAsFolders:(BOOL)arg4;
+ (int)findMatchingFileOrDirectory:(id)arg1 outPath:(id *)arg2 visibleOnly:(BOOL)arg3;
+ (BOOL)validPath:(id)arg1;
+ (BOOL)rename:(id)arg1 positions:(id)arg2 to:(id)arg3;
+ (id)pathFromRef:(const struct FSRef *)arg1;
+ (void)deleteResourceFork:(id)arg1;
+ (void)deleteDataFork:(id)arg1;
+ (void)setResourceFork:(id)arg1 length:(unsigned long long)arg2;
+ (void)setDataFork:(id)arg1 length:(unsigned long long)arg2;
+ (BOOL)moveFile:(id)arg1 toPath:(id)arg2;
+ (BOOL)hasNumFolders:(int)arg1 forDirectory:(id)arg2 treatPackagesAsFolders:(BOOL)arg3;
+ (id)permissionsTextForDesc:(id)arg1;
+ (id)permissionsTextForModeBits:(unsigned long)arg1;
+ (id)intToString:(unsigned int)arg1;
+ (unsigned int)stringToInt:(id)arg1;
+ (id)directoryContentsAtPath:(id)arg1;
+ (struct AEDesc)AEDescAliasList:(id)arg1;
+ (void)copy:(id)arg1 fromDataFork:(BOOL)arg2 to:(id)arg3 toDataFork:(BOOL)arg4;
+ (id)fullPathForApplication:(id)arg1;

@end

