//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFileDesc.h>

@interface NTFileDesc (Private)
+ (id)resolveAlias:(id)arg1 resolveIfServerAlias:(BOOL)arg2 isServerAlias:(char *)arg3;
- (void)initLSInfoRec;
- (id)getMountedVolumeInfo;
- (void)initVolumeInfo;
- (void)initVolumeParams;
- (id)resolvedDesc:(BOOL)arg1;
- (void)setAliasDesc:(id)arg1;
- (void)scanDirectoryContents;
- (id)carbonVersionString:(BOOL)arg1;
- (int)volumeSortRank:(id)arg1;
- (unsigned long long)volumeTotalBytes;
- (unsigned long long)volumeFreeBytes;
- (struct FSRef *)bootFSRef;
@end

