//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableArray;

@interface NTFileDescMemCache : NSObject
{
    NSLock *_threadLock;
    NSMutableArray *_free;
}

+ (void)initialize;
+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)checkout;
- (void)checkin:(id)arg1;

@end

