//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFindFilterThread.h>

@interface NTFindFilterThread (Private)
- (void)threadMethod;
- (BOOL)itemIsAMatch:(id)arg1 param:(id)arg2;
- (BOOL)isNameOK:(id)arg1 param:(id)arg2;
- (BOOL)isExtensionOK:(id)arg1 param:(id)arg2;
- (BOOL)isKindOK:(id)arg1 param:(id)arg2;
- (BOOL)isSearchFolderOK:(id)arg1 param:(id)arg2;
@end

