//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTThreadWorkerController;

@interface NTFileFinder : NSObject
{
    id _delegate;
    NTThreadWorkerController *_findThreadController;
}

- (id)initWithDelegate:(id)arg1;
- (void)dealloc;
- (void)findOutputNotification:(id)arg1;
- (void)findFile:(id)arg1 directories:(id)arg2;
- (BOOL)isFinding;
- (void)stopFinding;

@end

