//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFileLocator.h>

@interface NTFileLocator (Private)
- (BOOL)shouldSearchDesc:(id)arg1;
- (id)recursiveFindFiles:(id)arg1 level:(int)arg2 searchType:(int)arg3;
@end

