//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableArray;

@interface NTFileActivityMonitor : NSObject
{
    NSMutableArray *_activityMonitor;
    NSLock *_activityLock;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)directoryActivityStarted:(id)arg1;
- (void)directoryActivityFinished:(id)arg1;
- (BOOL)isVolumeBusy:(id)arg1;

@end

