//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString, NTFileDesc, NTIconPositions;

@interface NTFileActionRequest : NSObject
{
    int _fileAction;
    NSMutableArray *_srcDescs;
    NSMutableArray *_destPaths;
    NSString *_destFolder;
    NTFileDesc *_destFolderDesc;
    int _modifyFlags;
    NTFileActionRequest *_preRequest;
    NTFileActionRequest *_postRequest;
    NTIconPositions *_iconPositions;
}

+ (id)deleteRequestWithDesc:(id)arg1;
+ (id)deleteRequestWithDescs:(id)arg1;
- (id)initWithAction:(int)arg1 toFolder:(id)arg2;
- (void)dealloc;
- (id)initWithAction:(int)arg1 onItems:(id)arg2 toFolder:(id)arg3;
- (id)initWithAction:(int)arg1 onItem:(id)arg2 toFolder:(id)arg3 withName:(id)arg4;
- (id)initWithAction:(int)arg1 onItem:(id)arg2 withFlags:(int)arg3;
- (int)fileAction;
- (int)numRequests;
- (id)getSrcForRequest:(int)arg1;
- (id)getDestForRequest:(int)arg1;
- (id)destinationVolume;
- (id)destinationFolder;
- (id)destinationFolderDesc;
- (int)modifyFlags;
- (void)setIconPositions:(id)arg1;
- (id)iconPositions;
- (BOOL)preflightCheck;
- (id)preRequest;
- (id)postRequest;

@end

