//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFindByContent.h>

@interface NTFindByContent (Utilities)
+ (void)askUserToIndexFolder:(id)arg1 sheetWindow:(id)arg2;
+ (void)buildIndexSheetSelector:(id)arg1;
+ (BOOL)findByContentPreflightCheck:(id)arg1 sheetWindow:(id)arg2;
+ (BOOL)hasIndex:(id)arg1;
+ (BOOL)deleteIndex:(id)arg1;
+ (BOOL)reIndex:(id)arg1;
@end

