//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFindThreadManager.h>

@interface NTFindThreadManager (MainThread_Callbacks)
- (void)findIsComplete_Callback:(id)arg1;
- (void)resultsUpdated_Callback:(id)arg1;
- (void)findHaltedPrematurely_Callback:(id)arg1;
@end

