//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PrefsBoxDelegate.h"

@class NTPrefsBox, NTPrefsBoxMgr;

@interface NTFilePreferences : NSObject <PrefsBoxDelegate>
{
    NTPrefsBoxMgr *_prefsBoxMgr;
    NTPrefsBox *_prefsBox;
    BOOL _resolveAliases;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)setResolveAliases:(BOOL)arg1;
- (BOOL)resolveAliases;
- (void)prefsBoxModified:(id)arg1 forKey:(id)arg2;
- (id)requiresReloadPreferenceIDs;

@end

