//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NTFindControllerProtocol.h"

@class NTFindThreadManager;

@interface NTFindFile : NSObject <NTFindControllerProtocol>
{
    NSObject *_delegate;
    NTFindThreadManager *_threadManager;
}

- (id)initWithDelegate:(id)arg1;
- (void)dealloc;
- (void)find:(id)arg1 name:(id)arg2 nameMatchSpecifier:(int)arg3 extension:(id)arg4 kind:(int)arg5 type:(unsigned long)arg6 creator:(unsigned long)arg7 sizeSpecifier:(int)arg8 size:(float)arg9 sizeUnit:(int)arg10 label:(int)arg11 owner:(int)arg12 group:(int)arg13 access:(int)arg14 created:(int)arg15 modified:(int)arg16 visibility:(int)arg17 searchInsidePackages:(BOOL)arg18 searchInsideSystemFolder:(BOOL)arg19 negateParameters:(BOOL)arg20;
- (id)results:(char *)arg1;
- (void)findIsComplete_Callback:(id)arg1;
- (void)resultsUpdated_Callback:(id)arg1;
- (void)findHaltedPrematurely_Callback:(id)arg1;
- (void)stopFind;

@end

