//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFindParam.h>

@interface NTFindParam (Private)
- (void)buildSearchParams;
- (void)timeSpecsForDateSpec:(int)arg1 lower:(struct timespec *)arg2 upper:(struct timespec *)arg3;
@end

