//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet, NTFileDesc;

@interface NTFileLocator : NSObject
{
    int _maxSearchLevel;
    int _progressCounter;
    NTFileDesc *_desc;
    NSMutableSet *_visitedFolders;
}

- (id)initWithDesc:(id)arg1;
- (void)dealloc;
- (id)findImages:(int)arg1 maximumSearchLevel:(int)arg2;
- (id)findHTMLFiles:(int)arg1 maximumSearchLevel:(int)arg2;
- (id)findAllFiles:(int)arg1 maximumSearchLevel:(int)arg2;

@end

