//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFileRequestProcessor.h>

@interface NTFileRequestProcessor (Private)
- (BOOL)processCopyRequest;
- (BOOL)processMoveRequest;
- (BOOL)processDeleteRequest;
- (BOOL)processMakeMacAliasRequest:(BOOL)arg1;
- (BOOL)processMakeSymbolicLinkRequest;
- (BOOL)processModifyFileRequest;
- (void)doModifyFile:(id)arg1 withFlags:(int)arg2;
- (void)modifyFile:(id)arg1 withFlags:(int)arg2;
- (unsigned long long)calcFolderSize:(id)arg1;
- (void)doCalcSize;
- (BOOL)doCopy:(id)arg1 dest:(id)arg2 engine:(id)arg3;
- (void)sendErrorToDelegate:(id)arg1 error:(id)arg2;
- (void)sendPrepareProgressToDelegate:(id)arg1 itemsProcessed:(int)arg2;
- (void)setRequestCanceled:(BOOL)arg1;
- (BOOL)hasRequestBeenCanceled;
@end

