//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTFindThreadManager.h>

@interface NTFindThreadManager (Thread_Callbacks)
- (void)thread_appendResults:(id)arg1 results:(id)arg2;
- (void)thread_resetResults;
- (void)thread_findHaltedPrematurely;
- (id)thread_findThreadResults;
- (void)thread_threadDone:(id)arg1;
- (BOOL)thread_isFindThreadDone;
- (void)thread_setFindThreadDone;
@end

