//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableArray;

@interface NTFileNamingManager : NSObject
{
    NSLock *_lock;
    NSMutableArray *_nameReserve;
}

+ (void)initialize;
+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)reserveName:(id)arg1;
- (void)releaseName:(id)arg1;
- (BOOL)isUnique:(id)arg1;
- (id)uniqueName:(id)arg1 with:(id)arg2;

@end

