//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSConditionLock, NSLock, NSMutableArray, NTFindFile, NTFindFilterThread, NTFindThread;

@interface NTFindThreadManager : NSObject
{
    NTFindFile *_delegate;
    NTFindThread *_findThread;
    NTFindFilterThread *_filterThread;
    NSLock *_findResults_Lock;
    NSMutableArray *_findResults;
    BOOL _appendResults;
    NSLock *_findThreadResults_Lock;
    NSMutableArray *_findThreadResults;
    NSConditionLock *_findThreadDone;
}

- (id)initWithDelegate:(id)arg1;
- (void)dealloc;
- (void)stopFind;
- (id)findThread;
- (id)results:(char *)arg1;
- (void)setDelegateToNil;

@end

