//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTFileDesc;

@interface NTFindResult : NSObject
{
    NTFileDesc *_desc;
    float _relevance;
}

+ (id)result:(id)arg1 relevance:(float)arg2;
- (id)initWithDesc:(id)arg1 relevance:(float)arg2;
- (void)dealloc;
- (id)desc;
- (float)relevance;

@end

