//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NTFileDesc, NTFindParam;

@interface NTFoundFile : NSObject
{
    NSString *_fileName;
    NTFileDesc *_desc;
    int _parID;
    int _volumeRefNum;
    NTFindParam *_param;
}

+ (id)foundFile:(int)arg1 volumeRefNum:(int)arg2 name:(const char *)arg3 param:(id)arg4;
- (id)initWithParID:(int)arg1 volumeRefNum:(int)arg2 name:(const char *)arg3 param:(id)arg4;
- (void)dealloc;
- (id)desc;
- (id)param;

@end

