//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSString, NTPath;

@interface NTFSRefObject : NSObject
{
    struct FSRef _ref;
    BOOL _isValid;
    NTPath *_path;
    NSString *_name;
    NTFSRefObject *_parentRefObject;
    struct FSCatalogInfo _catalogInfo;
    unsigned int _catalogInfoBitmap;
}

+ (id)refObject:(const struct FSRef *)arg1;
+ (id)refObject:(const struct FSRef *)arg1 updatedFor:(unsigned long)arg2;
+ (id)refObject:(const struct FSRef *)arg1 name:(id)arg2 parentRef:(id)arg3 updatedFor:(unsigned long)arg4;
+ (id)refObject:(const struct FSRef *)arg1 catalogInfo:(struct FSCatalogInfo *)arg2 bitmap:(unsigned long)arg3 name:(id)arg4 parentRef:(id)arg5;
+ (id)refObjectWithNTPath:(id)arg1 resolvePath:(BOOL)arg2;
- (id)initWithRef:(const struct FSRef *)arg1 catalogInfo:(struct FSCatalogInfo *)arg2 bitmap:(unsigned long)arg3 name:(id)arg4 parentRef:(id)arg5 updatedFor:(unsigned long)arg6;
- (id)initWithRef:(const struct FSRef *)arg1 catalogInfo:(struct FSCatalogInfo *)arg2 bitmap:(unsigned long)arg3 name:(id)arg4 parentRef:(id)arg5;
- (id)initWithNTPath:(id)arg1 resolvePath:(BOOL)arg2;
- (void)dealloc;
- (struct FSRef *)ref;
- (BOOL)isValid;
- (id)ntPath;
- (id)name;
- (BOOL)isNameLocked;
- (BOOL)isLocked;
- (int)valence;
- (id)modificationDate;
- (id)creationDate;
- (id)attributeModificationDate;
- (id)accessDate;
- (const struct FileInfo *)fileInfo;
- (short)volumeRefNum;
- (id)icon;
- (BOOL)isFile;
- (BOOL)isDirectory;
- (unsigned int)parentDirID;
- (BOOL)parentIsVolume;
- (BOOL)isVolume;
- (unsigned long)fileType;
- (unsigned long)fileCreator;
- (BOOL)isStationery;
- (BOOL)isBundleBitSet;
- (BOOL)isAliasBitSet;
- (int)fileLabel;
- (struct _NSPoint)finderPosition;
- (BOOL)isInvisible;
- (BOOL)isCarbonAlias;
- (BOOL)hasCustomIcon;
- (BOOL)isSymbolicLink;
- (unsigned long)ownerID;
- (id)ownerName;
- (unsigned long)groupID;
- (id)groupName;
- (unsigned int)nodeID;
- (unsigned short)modeBits;
- (unsigned char)sharingFlags;
- (BOOL)stillExists;
- (BOOL)hasBeenModified;
- (id)parentFSRef;
- (id)URL;
- (unsigned long long)rsrcForkSize;
- (unsigned long long)dataForkSize;
- (BOOL)updateCatalogInfo:(unsigned long)arg1;
- (struct FSCatalogInfo *)catalogInfo;
- (unsigned long)catalogInfoBitmap;
- (BOOL)isParentOfFSRef:(const struct FSRef *)arg1;

@end

