//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface NTGridDataSet : NSObject <NSCoding>
{
    NSString *_name;
    NSMutableArray *_dataArray;
    NSMutableDictionary *_coordinateDictionary;
    int _layoutStyle;
    unsigned int _itemSize;
    struct _NSPoint _maxCoordinate;
}

- (void)commonInit;
- (id)initWithName:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned int)itemSize;
- (void)setItemSize:(unsigned int)arg1;
- (void)setLayoutStyle:(int)arg1;
- (int)layoutStyle;
- (id)name;
- (unsigned int)numberOfItems;
- (struct _NSPoint)coordinateAtIndex:(int)arg1;
- (void)setCoordinate:(struct _NSPoint)arg1 atIndex:(int)arg2;
- (id)drawingCacheAtIndex:(int)arg1;
- (id)drawingCacheWithCoordinate:(struct _NSPoint)arg1;
- (void)setDrawingCache:(id)arg1 atIndex:(int)arg2;
- (void)setDrawingCache:(id)arg1 withCoordinate:(struct _NSPoint)arg2;
- (id)objectAtIndex:(unsigned int)arg1;
- (void)removeObjectAtIndex:(unsigned int)arg1;
- (id)objectWithCoordinate:(struct _NSPoint)arg1;
- (void)addObject:(id)arg1;
- (void)addObject:(id)arg1 withCoordinate:(struct _NSPoint)arg2;
- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2 withCoordinate:(struct _NSPoint)arg3;
- (void)insertObject:(id)arg1 atIndex:(unsigned int)arg2;
- (void)removeObjectWithCoordinate:(struct _NSPoint)arg1;
- (void)removeAllObjects;
- (struct _NSPoint)maxCoordinate;
- (BOOL)someCoordinatesNeedLayout;

@end

