//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTGrid.h>

@interface NTGrid (Private)
- (void)doDrawRect:(struct _NSRect)arg1;
- (void)setFrameSize:(struct _NSSize)arg1;
- (void)declareDragging;
- (id)draggingObjects:(id)arg1;
- (void)drawGrid:(id)arg1;
- (void)resetTooltips;
- (id)view:(id)arg1 stringForToolTip:(int)arg2 point:(struct _NSPoint)arg3 userData:(void *)arg4;
- (id)hintTextAtPoint:(struct _NSPoint)arg1;
- (void)cleanUpAfterDragDrop;
- (void)displayContextualMenu:(struct _NSPoint)arg1 event:(id)arg2;
- (void)invalidatePreviousDragDropIndicators;
- (void)performSpringLoadedFolder;
- (void)clearDragSelection;
- (void)startSpringLoadedTimer:(id)arg1 onObject:(id)arg2 withCoordinate:(struct _NSPoint)arg3;
@end

