//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@interface NTGridDataObject : NSObject <NSCoding>
{
    struct _NSPoint _coordinate;
    id _data;
    id _drawingCache;
}

+ (id)dataObject:(id)arg1;
+ (id)dataObject:(id)arg1 withCoordinate:(struct _NSPoint)arg2;
- (id)initWithData:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)data;
- (void)setDrawingCache:(id)arg1;
- (id)drawingCache;
- (struct _NSPoint)coordinate;
- (void)setCoordinate:(struct _NSPoint)arg1;
- (BOOL)hasValidCoordinate;

@end

