//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTIconStore.h>

@interface NTIconStore (Private)
- (void)registerIcons;
- (void)registerIconFile:(id)arg1 withType:(unsigned long)arg2;
- (BOOL)registerImageFile:(id)arg1 withType:(unsigned long)arg2;
- (BOOL)registerImage:(id)arg1 withType:(unsigned long)arg2;
- (id)iconFromSystemIconsBundleWithName:(id)arg1;
@end

