//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTIconCompositor : NSObject
{
}

+ (void)drawIconFor:(id)arg1 inRect:(struct _NSRect)arg2 drawLabel:(BOOL)arg3 flip:(BOOL)arg4;
+ (void)drawIconFor:(id)arg1 inRect:(struct _NSRect)arg2 selected:(BOOL)arg3 opened:(BOOL)arg4 drawLabel:(BOOL)arg5 flip:(BOOL)arg6;
+ (void)drawIconForRef:(struct OpaqueIconRef *)arg1 inRect:(struct _NSRect)arg2 label:(int)arg3 selected:(BOOL)arg4 opened:(BOOL)arg5 flip:(BOOL)arg6;
+ (void)drawIconForRef:(struct OpaqueIconRef *)arg1 inRect:(struct _NSRect)arg2 label:(int)arg3 selected:(BOOL)arg4 opened:(BOOL)arg5 flip:(BOOL)arg6 alpha:(float)arg7;

@end

