//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTIconFamily.h>

@interface NTIconFamily (ScrapAdditions)
+ (BOOL)canInitWithScrap;
+ (id)iconFamilyWithScrap;
- (id)initWithScrap;
- (BOOL)putOnScrap;
@end

