//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTIcon : NSObject
{
    struct OpaqueIconRef *_iconRef;
}

+ (id)iconWithRef:(struct OpaqueIconRef *)arg1;
- (id)initWithRef:(struct OpaqueIconRef *)arg1;
- (void)dealloc;
- (struct OpaqueIconRef *)iconRef;
- (id)imageForSize:(int)arg1 label:(int)arg2 select:(BOOL)arg3;
- (id)imageForSize:(int)arg1 label:(int)arg2 select:(BOOL)arg3 alpha:(float)arg4;

@end

