//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTIcon;

@interface NTIconStore : NSObject
{
    BOOL _useFinderIcons;
    BOOL _useAlternateEmptyTrash;
    BOOL _useAlternateFullTrash;
    NTIcon *_aliasBadge;
    NTIcon *_lockBadge;
    NTIcon *_scriptBadge;
    NTIcon *_computerIcon;
    NTIcon *_documentIcon;
    NTIcon *_folderIcon;
    NTIcon *_trashIcon;
    NTIcon *_trashFullIcon;
    NTIcon *_ejectIcon;
    NTIcon *_backwardsIcon;
    NTIcon *_forwardsIcon;
    NTIcon *_connectToIcon;
    NTIcon *_idiskIcon;
    NTIcon *_idiskPublicIcon;
    NTIcon *_fileServerIcon;
    NTIcon *_CDROMIcon;
    NTIcon *_hardDiskIcon;
    NTIcon *_finderIcon;
    NTIcon *_desktopIcon;
    NTIcon *_deleteIcon;
    NTIcon *_favoritesIcon;
    NTIcon *_homeIcon;
    NTIcon *_windowIcon;
    NTIcon *_publicIcon;
    NTIcon *_picturesIcon;
    NTIcon *_newFolderIcon;
    NTIcon *_musicIcon;
    NTIcon *_moviesIcon;
    NTIcon *_infoIcon;
    NTIcon *_findIcon;
    NTIcon *_documentsIcon;
    NTIcon *_applicationsIcon;
    NTIcon *_noWriteIcon;
    NTIcon *_drawerIcon;
    NTIcon *_burnIcon;
    NTIcon *_textDocumentIcon;
    NTIcon *_clippingsDocumentIcon;
    NTIcon *_previewIcon;
    NTIcon *_recentItemsIcon;
    NTIcon *_eraseIcon;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)iconForSystemType:(unsigned long)arg1;
- (id)iconForType:(unsigned long)arg1 creator:(unsigned long)arg2;
- (id)aliasBadge;
- (id)lockBadge;
- (id)appleScriptBadge;
- (id)documentIcon;
- (id)noWriteIcon;
- (id)folderIcon;
- (id)trashIcon;
- (id)trashFullIcon;
- (id)ejectIcon;
- (id)backwardsIcon;
- (id)forwardsIcon;
- (id)connectToIcon;
- (id)fileServerIcon;
- (id)CDROMIcon;
- (id)iDiskIcon;
- (id)iDiskPublicIcon;
- (id)hardDiskIcon;
- (id)homeIcon;
- (id)favoritesIcon;
- (id)deleteIcon;
- (id)finderIcon;
- (id)desktopIcon;
- (id)burnIcon;
- (id)eraseIcon;
- (id)recentItemsIcon;
- (id)windowIcon;
- (id)publicIcon;
- (id)computerIcon;
- (id)picturesIcon;
- (id)newFolderIcon;
- (id)musicIcon;
- (id)moviesIcon;
- (id)infoIcon;
- (id)findIcon;
- (id)previewIcon;
- (id)documentsIcon;
- (id)applicationsIcon;
- (id)drawerIcon;
- (id)textDocumentIcon;
- (id)clippingsDocumentIcon;

@end

