//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage;

@interface NTImagePasteboardSource : NSObject
{
    NSImage *_image;
}

+ (id)image:(id)arg1 toPasteboard:(id)arg2;
- (id)initWithImage:(id)arg1;
- (void)dealloc;

@end

