//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTImageView.h>

@interface NTImageView (Private)
- (id)imageForDrag;
- (id)backgroundImage;
- (void)drawBackgroundPattern:(struct _NSRect)arg1;
- (struct _NSRect)startZoomRect;
- (void)performDrag:(id)arg1;
- (void)convertToCachedImage;
@end

