//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTInfoView.h>

@interface NTInfoView (Private)
- (void)resetForNewItem;
- (void)createInfoView;
- (void)updateInfoView;
- (id)infoPairs;
- (void)startCalcSizeThread;
- (void)calcFolderSizeButton:(id)arg1;
- (void)sizeCalcNotification:(id)arg1;
- (id)longInfoPairs;
- (id)sizePairs:(BOOL)arg1;
- (void)setFolderSizeInfo:(id)arg1 totalValence:(id)arg2;
@end

