//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTItemPosition : NSObject
{
    NSString *_path;
    struct _NSPoint _position;
}

+ (id)itemWithPath:(id)arg1 position:(struct _NSPoint)arg2;
- (id)initWithPath:(id)arg1 position:(struct _NSPoint)arg2;
- (void)dealloc;
- (struct _NSPoint)position;
- (id)path;

@end

