//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface NTLabelColorMgr : NSObject
{
    NSMutableArray *_labelColors;
}

+ (id)sharedInstance;
- (void)dealloc;
- (id)init;
- (int)compare:(int)arg1 label2:(int)arg2;
- (id)color:(int)arg1;
- (struct RGBColor *)rgbColor:(int)arg1;
- (id)label:(int)arg1;
- (id)labelPopUpMenu;
- (id)labelMenu;

@end

