//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTLaunchServices : NSObject
{
}

+ (BOOL)launchDescs:(id)arg1 withApp:(id)arg2;
+ (BOOL)launchDescs:(id)arg1 withApp:(id)arg2 launchFlags:(unsigned long)arg3;

@end

