//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTMenu.h>

@interface NTMenu (Private)
- (void)addItemToMenu:(id)arg1 title:(id)arg2 tag:(int)arg3 subMenu:(id)arg4 icon:(id)arg5 obj:(id)arg6 key:(id)arg7 mask:(int)arg8 sel:(SEL)arg9 target:(id)arg10;
- (id)mutableItems;
@end

