//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTPDFPreviewView.h>

@interface NTPDFPreviewView (Private)
- (struct _NSRect)paperRectForPage:(int)arg1;
- (void)updateFrame;
- (float)pageWidth;
- (float)pageHeight;
- (void)drawPageNumber:(int)arg1 inRect:(struct _NSRect)arg2;
- (struct _NSRect)startZoomRect;
@end

