//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTPDFImageView.h>

@interface NTPDFImageView (Printing)
- (BOOL)knowsPageRange:(struct _NSRange *)arg1;
- (struct _NSRect)rectForPage:(int)arg1;
@end

