//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NTPDFFile;

@interface NTPDFPreviewView : NSView
{
    int _numPages;
    int _spaceBetweenPages;
    NTPDFFile *_pdfFile;
    struct _NSRect _pfdPageBounds;
}

+ (id)pdfImageView:(struct _NSRect)arg1;
- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (void)viewFrameChanged:(id)arg1;
- (void)setDesc:(id)arg1;
- (void)drawRect:(struct _NSRect)arg1;
- (void)gotoPage:(int)arg1;
- (int)numberOfPages;
- (int)currentPage;
- (BOOL)isFlipped;
- (void)mouseDown:(id)arg1;

@end

