//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTPDFImageView.h>

@interface NTPDFImageView (Private)
- (struct _NSRect)paperRectForPage:(int)arg1;
- (void)updateFrame;
- (void)drawPageNumber:(int)arg1 inRect:(struct _NSRect)arg2;
- (int)doBinPageSearch:(struct _NSPoint)arg1 lowIndex:(int)arg2 highIndex:(int)arg3;
- (int)pageAtPoint:(struct _NSPoint)arg1;
- (void)doDrawRect:(struct _NSRect)arg1;
- (void)doPrintRect:(struct _NSRect)arg1;
@end

