//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSButton, NTFileDesc;

@interface NTPlayClassicSoundView : NSView
{
    NTFileDesc *_desc;
    NSButton *_playButton;
}

- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (void)setSound:(id)arg1;

@end

