//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTPlayClassicSoundView.h>

@interface NTPlayClassicSoundView (Private)
- (void)centerButton;
- (void)viewFrameChanged:(id)arg1;
- (void)addPlayButton;
- (void)playSoundAction:(id)arg1;
@end

