//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTResolvedServerAliasCache.h>

@interface NTResolvedServerAliasCache (Private)
- (id)findAliasInCache:(id)arg1;
- (void)addEntryToCache:(id)arg1;
- (void)removeEntryFromCache:(id)arg1;
@end

