//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSDictionary, NTFileDesc;

@interface NTResourceMgr : NSObject
{
    BOOL _isValid;
    BOOL _useDataFork;
    NSDictionary *_resourceMap;
    NSData *_fileData;
    NTFileDesc *_desc;
}

+ (id)mgrWithDesc:(id)arg1 useDataFork:(BOOL)arg2;
+ (id)mgrWithDesc:(id)arg1;
- (id)initWithDesc:(id)arg1 useDataFork:(BOOL)arg2;
- (void)dealloc;
- (BOOL)isValid;
- (id)resourceForType:(unsigned long)arg1;
- (id)resourceForType:(unsigned long)arg1 resID:(int)arg2;
- (id)resourceTypes;
- (id)resouceIDsForType:(unsigned long)arg1;
- (id)resourceInfosForType:(unsigned long)arg1;

@end

