//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTResourceFork : NSObject
{
    short fileReference;
}

+ (id)resourceForkForReadingAtURL:(id)arg1;
+ (id)resourceForkForWritingAtURL:(id)arg1;
+ (id)resourceForkForReadingAtPath:(id)arg1;
+ (id)resourceForkForWritingAtPath:(id)arg1;
- (id)initForReadingAtURL:(id)arg1;
- (id)initForWritingAtURL:(id)arg1;
- (id)initForPermission:(BOOL)arg1 AtURL:(id)arg2;
- (id)initForPermission:(BOOL)arg1 AtPath:(id)arg2;
- (id)initForReadingAtPath:(id)arg1;
- (id)initForWritingAtPath:(id)arg1;
- (void)dealloc;
- (BOOL)addData:(id)arg1 type:(unsigned long)arg2 Id:(short)arg3 name:(id)arg4;
- (id)dataForType:(unsigned long)arg1 Id:(short)arg2;
- (BOOL)addString:(id)arg1 type:(unsigned long)arg2 Id:(short)arg3 name:(id)arg4;
- (id)stringForType:(unsigned long)arg1 Id:(short)arg2;
- (BOOL)removeType:(unsigned long)arg1 Id:(short)arg2;

@end

