//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTRMTask.h>

@interface NTRMTask (Private)
- (void)prepareForDelete:(id)arg1;
- (void)delegate_handleTaskErrors:(id)arg1;
- (void)delegate_handleTaskOutput:(id)arg1;
- (void)delegate_handleTaskFinished:(id)arg1;
@end

