//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDate, NSString, NTFileDesc, NTProgressBar, NTRMTask;

@interface NTRMThread : NSObject
{
    NTRMTask *_rmTask;
    NSArray *_descs;
    NTFileDesc *_currentDesc;
    BOOL _asRoot;
    int _securityLevel;
    NSString *_destFolderName;
    NTProgressBar *_progressBar;
    NSDate *_lastUpdate;
    BOOL _firstCopyProgressCall;
    BOOL _endRunLoop;
}

+ (void)deleteDesc:(id)arg1 asRoot:(BOOL)arg2 securityLevel:(int)arg3;
+ (void)deleteDescs:(id)arg1 asRoot:(BOOL)arg2 securityLevel:(int)arg3;
- (id)initWithDescs:(id)arg1 asRoot:(BOOL)arg2 securityLevel:(int)arg3;
- (void)dealloc;
- (void)performDelete:(id)arg1;
- (void)delegate_NTRMTaskProgress:(id)arg1;
- (void)delegate_NTRMTaskFinished:(id)arg1;

@end

