//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTSearchThread.h>

@interface NTSearchThread (Private)
- (void)sendResults;
- (void)findFile:(id)arg1 inDirectory:(id)arg2;
- (void)catalogSearch:(id)arg1 inDirectory:(id)arg2 filterResults:(BOOL)arg3;
- (void)folderSearcher:(id)arg1 inDirectory:(id)arg2;
@end

