//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTThreadWorker.h"

@class NSDate, NSMutableArray, NTSearchThreadParam;

@interface NTSearchThread : NTThreadWorker
{
    NTSearchThreadParam *_param;
    NSDate *_lastTimeSentResults;
    NSMutableArray *_results;
    BOOL _packagesAreFolders;
    int _numResultSent;
}

- (void)dealloc;
- (BOOL)doWorkerMethod:(id)arg1;

@end

