//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTFileDesc;

@interface NTServerCacheEntry : NSObject
{
    NTFileDesc *_alias;
    NTFileDesc *_resolved;
}

+ (id)entry:(id)arg1 resolved:(id)arg2;
+ (id)cacheKeyForAlias:(id)arg1;
- (id)initWithAlias:(id)arg1 resolved:(id)arg2;
- (void)dealloc;
- (id)alias;
- (id)resolved;
- (id)cacheKey;

@end

