//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface NTSearchThreadParam : NSObject
{
    NSString *_findString;
    NSArray *_directories;
    NSArray *_resultDescs;
    BOOL _finished;
}

+ (id)threadedFindParam:(id)arg1 directories:(id)arg2;
- (id)initWithString:(id)arg1 directories:(id)arg2;
- (void)dealloc;
- (id)findString;
- (id)directories;
- (void)setOutput:(id)arg1;
- (id)output;
- (void)setFinished:(BOOL)arg1;
- (BOOL)finished;

@end

