//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock, NSMutableSet;

@interface NTStringShare : NSObject
{
    NSLock *_kindLock;
    NSLock *_extensionLock;
    NSMutableSet *_kindStrings;
    NSMutableSet *_extensionStrings;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)sharedKindString:(id)arg1;
- (id)sharedExtensionString:(id)arg1;

@end

