//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, NTFileActionRequest, NTProgressBar;

@interface NTThreadedFileRequest : NSObject
{
    NTFileActionRequest *_request;
    NSString *_destFolderName;
    NTProgressBar *_progressBar;
    NSDate *_lastUpdate;
    BOOL _firstCopyProgressCall;
    BOOL _destinationIsWebDAV;
}

- (id)initWithRequest:(id)arg1;
- (void)dealloc;
- (void)doRequest:(id)arg1;
- (BOOL)delegate_displayErrorAtPath:(id)arg1 error:(id)arg2;
- (BOOL)delegate_copyProgress:(id)arg1 bytesCopied:(unsigned long long)arg2 totalBytes:(unsigned long long)arg3 itemsCopied:(int)arg4 totalItems:(int)arg5;
- (BOOL)delegate_deleteProgress:(id)arg1;
- (BOOL)delegate_copyPreparation:(id)arg1 itemsProcessed:(int)arg2;

@end

