//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSConditionLock, NSConnection, NTFindThreadManager;

@interface NTThreadCommon : NSObject
{
    NSConnection *_connectionInMain;
    NSConnection *_connectionInThread;
    NTFindThreadManager *_delegate;
    id _param;
    NSConditionLock *_threadState;
    BOOL _endRunLoop;
    NSConditionLock *_conditionLock;
}

- (id)initWithDelegate:(id)arg1;
- (void)dealloc;
- (void)startThread:(id)arg1;
- (void)setThreadState:(int)arg1;
- (int)threadState;
- (void)cancelThread;
- (BOOL)threadCancelled;
- (void)signalThread;
- (void)waitForSignal;
- (void)performSelectorOnDelegateThread:(SEL)arg1;

@end

