//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSArray, NSString, NTThreadWorkerController;

@interface NTUsersAndGroups : NSObject
{
    BOOL _isRoot;
    NSString *_userName;
    unsigned int _userID;
    unsigned int _groupID;
    NSArray *_userGroups;
    NSArray *_users;
    NSArray *_groups;
    NTThreadWorkerController *_loadThread;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (void)loadThreadNotification:(id)arg1;
- (id)userName;
- (unsigned long)userID;
- (unsigned long)groupID;
- (BOOL)isRoot;
- (BOOL)userIsMember:(id)arg1;
- (id)userGroups;
- (id)groupList;
- (id)userList;
- (id)groupName:(int)arg1;
- (id)userName:(int)arg1;
- (int)groupID:(id)arg1;
- (int)userID:(id)arg1;
- (id)groupMenu;
- (id)userMenu;

@end

