//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTVolume.h>

@interface NTVolume (Private)
- (void)makeStatFS:(id)arg1;
- (void)checkParents:(unsigned int)arg1 parts:(id *)arg2;
- (id)formatInterfaceInfo:(char *)arg1;
- (BOOL)thing:(unsigned int)arg1 conformsTo:(const char *)arg2 inRegistryPlane:(const char *)arg3;
- (BOOL)isFirewireDevice:(char *)arg1;
@end

