//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTVolumeMgr.h>

@interface NTVolumeMgr (Utils)
+ (BOOL)userVolumeAtMountPoint:(id)arg1;
+ (id)mountedVolumes:(BOOL)arg1;
@end

