//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString, NSURL, NTFileDesc;

@interface NTVolume : NSObject
{
    short _vRefNum;
    struct FSRef _mountPointFSRef;
    NTFileDesc *_fileDesc;
    struct FSVolumeInfo _volumeInfo;
    struct statfs _statfs;
    int _driveType;
    NSString *_driveName;
    NSString *_mountPoint;
    NSString *_diskIDString;
    NSString *_fileSystemName;
    NSString *_mountDevice;
    NSString *_driveInfoString;
    NSURL *_url;
    unsigned long long _totalBytes;
    unsigned long long _freeBytes;
    NSDate *_createDate;
    NSDate *_modifyDate;
    NSDate *_backupDate;
    NSDate *_checkedDate;
    int _userViewableVolume;
    int _isFirewire;
}

+ (id)volumeWithRefNum:(short)arg1 mountPoint:(struct FSRef)arg2 volumeInfo:(struct FSVolumeInfo *)arg3;
+ (id)volumeWithRefNum:(short)arg1;
+ (id)volumeWithDesc:(id)arg1;
- (id)initWithRefNum:(short)arg1 mountPoint:(struct FSRef)arg2 volumeInfo:(struct FSVolumeInfo *)arg3;
- (void)dealloc;
- (BOOL)isUserViewable;
- (unsigned long long)totalBytes;
- (unsigned long long)freeBytes;
- (short)volumeRefNum;
- (struct FSRef *)mountPointFSRef;
- (id)mountPointFileDesc;
- (struct FSVolumeInfo *)volumeInfo;
- (id)mountPoint;
- (id)volumeURL;
- (id)mountDevice;
- (id)fileSystemName;
- (id)driveName;
- (id)diskIDString;
- (int)driveType;
- (BOOL)isAFP;
- (BOOL)isHFS;
- (BOOL)isUFS;
- (BOOL)isMSDOS;
- (BOOL)isAudioCD;
- (BOOL)isCDROM;
- (BOOL)isDVDROM;
- (BOOL)isNFS;
- (BOOL)isSAMBA;
- (BOOL)isCIFS;
- (BOOL)isWebDAV;
- (id)description;
- (id)createDate;
- (id)modifyDate;
- (id)backupDate;
- (id)checkedDate;
- (unsigned long)fileCount;
- (unsigned long)folderCount;
- (unsigned long)blockSize;
- (unsigned long)totalBlocks;
- (unsigned long)freeBlocks;
- (unsigned long)nextAllocation;
- (unsigned long)rsrcClumpSize;
- (unsigned long)dataClumpSize;
- (unsigned long)nextCatalogID;
- (unsigned short)flags;
- (unsigned short)filesystemID;
- (unsigned short)signature;
- (unsigned short)driveNumber;
- (short)driverRefNum;
- (id)driveInfoString;
- (BOOL)isFirewire;

@end

