//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, NTFileDesc;

@interface NTVolumeMounter : NSObject
{
    struct OpaqueFSVolumeOperation *_volumeOp;
    CDUnknownFunctionPointerType _mountUPP;
    CDUnknownFunctionPointerType _ejectUPP;
    CDUnknownFunctionPointerType _unmountUPP;
    NTFileDesc *_desc;
    NSURL *_url;
    NSString *_notificationName;
}

+ (void)eject:(id)arg1;
+ (void)mountVolumeWithURL:(id)arg1 user:(id)arg2 password:(id)arg3 notifyWhenMounts:(id)arg4;
+ (void)unmountVolume:(id)arg1;
+ (void)ejectVolume:(id)arg1;
+ (void)mountVolumeWithScheme:(id)arg1 host:(id)arg2 path:(id)arg3 user:(id)arg4 password:(id)arg5 notifyWhenMounts:(id)arg6;
- (id)init;
- (void)dealloc;

@end

