//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAttributedString, NSString, NSURL;

@interface NTWeblocFile : NSObject
{
    NSAttributedString *_attributedString;
    NSString *_displayName;
    NSURL *_url;
}

+ (BOOL)isHTTPWeblocFile:(id)arg1;
+ (BOOL)isServerWeblocFile:(id)arg1;
+ (id)urlFromWeblocFile:(id)arg1;
+ (id)stringFromWeblocFile:(id)arg1;
+ (BOOL)isTextWeblocFile:(id)arg1;
+ (id)weblocWithDesc:(id)arg1;
+ (id)weblocWithString:(id)arg1;
+ (id)weblocWithURL:(id)arg1;
- (id)initWithDesc:(id)arg1;
- (void)dealloc;
- (BOOL)isHTTPWeblocFile;
- (BOOL)isServerWeblocFile;
- (id)url;
- (BOOL)isTextWeblocFile;
- (id)attributedString;
- (void)saveToFile:(id)arg1;
- (void)saveToFile:(id)arg1 hideExtension:(BOOL)arg2;
- (void)setDisplayName:(id)arg1;
- (id)displayName;

@end

