//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechFoundation/NTWeblocFile.h>

@interface NTWeblocFile (Private)
+ (id)extractUrlFromWeblocFile:(id)arg1;
+ (id)extractStringFromWeblocFile:(id)arg1;
+ (id)readEntriesFromWeblocFile:(id)arg1;
- (void)setURL:(id)arg1;
- (void)setString:(id)arg1;
- (id)dragDataWithEntries:(id)arg1;
@end

