//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NTThreadWorker.h"

@interface SizeCalculatorThread : NTThreadWorker
{
    unsigned long long _numBytes;
    unsigned long long _numItems;
}

- (BOOL)doWorkerMethod:(id)arg1;

@end

