//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface SizeCalculatorParam : NSObject
{
    NSArray *_tokenArray;
    NSMutableArray *_resultsArray;
}

+ (id)paramWithTokens:(id)arg1;
- (id)initWithTokens:(id)arg1;
- (void)dealloc;
- (id)tokenArray;
- (id)resultsArray;

@end

