//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface UsersAndGroupsThreadParam : NSObject
{
    NSString *_userName;
    NSArray *_users;
    NSArray *_groups;
    NSArray *_userGroups;
}

+ (id)paramWithUserName:(id)arg1;
- (id)initWithUserName:(id)arg1;
- (void)dealloc;
- (id)userName;
- (id)users;
- (void)setUsers:(id)arg1;
- (id)groups;
- (void)setGroups:(id)arg1;
- (id)userGroups;
- (void)setUserGroups:(id)arg1;

@end

