//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WLDragMapEntry : NSObject
{
    unsigned int _type;
    short _resID;
}

+ (id)entryWithType:(unsigned long)arg1 resID:(int)arg2;
- (id)initWithType:(unsigned long)arg1 resID:(int)arg2;
- (unsigned long)type;
- (short)resID;
- (id)entryData;

@end

