//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Function Pointers

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    float x;
    float y;
};

struct CGSize {
    float _field1;
    float _field2;
};

struct FSRef {
    unsigned char _field1[80];
};

struct FSSpec {
    short _field1;
    long _field2;
    unsigned char _field3[64];
};

struct FileInfo {
    unsigned int _field1;
    unsigned int _field2;
    unsigned short _field3;
    struct Point _field4;
    unsigned short _field5;
};

struct HFSUniStr255 {
    unsigned short _field1;
    unsigned short _field2[255];
};

struct Point {
    short _field1;
    short _field2;
};

struct RGBColor {
    unsigned short _field1;
    unsigned short _field2;
    unsigned short _field3;
};

struct SndChannel {
    struct SndChannel *_field1;
    char *_field2;
    CDUnknownFunctionPointerType _field3;
    long _field4;
    long _field5;
    struct SndCommand _field6;
    short _field7;
    short _field8;
    short _field9;
    short _field10;
    struct SndCommand _field11[128];
};

struct SndCommand {
    unsigned short cmd;
    short param1;
    long param2;
};

struct UTCDateTime {
    unsigned short _field1;
    unsigned int _field2;
    unsigned short _field3;
};

struct _NSPoint {
    float x;
    float y;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct _NSRect {
    struct _NSPoint origin;
    struct _NSSize size;
};

struct _NSSize {
    float width;
    float height;
};

