//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface NotificationEntry : NSObject
{
    NSDictionary *_userInfo;
    NSString *_name;
}

+ (id)newEntry:(id)arg1 withName:(id)arg2;
- (id)initWithData:(id)arg1 withName:(id)arg2;
- (void)dealloc;
- (id)name;
- (id)userInfo;

@end

