//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEvent.h"

@interface NSEvent (ModifierKeys)
+ (BOOL)controlKeyDownNow;
+ (BOOL)optionKeyDownNow;
+ (BOOL)commandKeyDownNow;
+ (BOOL)shiftKeyDownNow;
- (BOOL)controlKeyDown;
- (BOOL)optionKeyDown;
- (BOOL)commandKeyDown;
- (BOOL)shiftKeyDown;
- (BOOL)optionXOrCommandKeyDown;
- (BOOL)shouldOpenNewWindowEvent;
@end

