//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSGeometry_NTExtensions : NSObject
{
}

+ (struct _NSRect)rectFromPoint:(struct _NSPoint)arg1 andPoint:(struct _NSPoint)arg2;
+ (struct _NSRect)rect:(struct _NSRect)arg1 centeredIn:(struct _NSRect)arg2 scaleToFitContainer:(BOOL)arg3;

@end

