//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenu.h"

@interface NSMenu (NTExtensions_Private)
+ (BOOL)recursiveMenuWalk:(id)arg1 menuRef:(struct OpaqueMenuRef *)arg2 menuID:(int)arg3 menuItem:(int)arg4;
+ (void)changeChecksToBullets:(struct OpaqueMenuRef *)arg1;
- (void)triggerMenuRefCreation;
@end

