//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMenu.h"

@interface NSMenu (NTExtensions)
+ (void)recursiveChangeFont:(struct OpaqueMenuRef *)arg1 font:(short)arg2 size:(unsigned short)arg3;
+ (void)setSmallFont:(struct OpaqueMenuRef *)arg1 size:(int)arg2;
+ (id)findMenuItemPath:(struct OpaqueMenuRef *)arg1 menuID:(int)arg2 menuItem:(int)arg3;
+ (struct Point)convertGlobalPointToCarbonPoint:(struct _NSPoint)arg1;
- (struct OpaqueMenuRef *)carbonMenu;
- (void)popupMenuBelowRect:(struct _NSRect)arg1 inView:(id)arg2 size:(int)arg3;
- (void)sendActionAtPath:(id)arg1;
@end

