//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (compare)
- (BOOL)containsDigit;
- (id)stringWithDigitsPadded;
- (id)numericCompareString;
- (int)nameCompare:(id)arg1;
- (int)compareSubString:(id)arg1;
@end

