//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (NTCarbonUtilities)
+ (id)stringWithFSRef:(const struct FSRef *)arg1;
- (BOOL)getFSRef:(struct FSRef *)arg1;
- (id)resolveAliasFile;
@end

