//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Utilities)
+ (id)stringWithFileSystemRepresentation:(const char *)arg1;
+ (id)stringWithPString:(unsigned char [256])arg1;
+ (id)stringWithHFSUniStr255:(const struct HFSUniStr255 *)arg1;
- (void)getPString:(unsigned char [256])arg1;
- (void)getHFSUniStr255:(struct HFSUniStr255 *)arg1;
- (id)stringByReplacing:(id)arg1 with:(id)arg2;
- (id)stringByReplacingValuesInArray:(id)arg1 withValuesInArray:(id)arg2;
- (id)stringByDeletingSuffix:(id)arg1;
- (id)stringWithShellCharactersQuoted;
- (id)stringWithShellCharactersQuotedold;
- (BOOL)stringContainsValueFromArray:(id)arg1;
- (BOOL)isEqualToStringCaseInsensitive:(id)arg1;
- (id)linesFromString:(id *)arg1;
- (id)getFirstLine;
- (id)stringWithRegularExpressionCharactersQuoted;
- (id)URLEncodedString;
- (id)HFSPath;
- (id)POSIXPath;
- (BOOL)isEndOfWordAtIndex:(unsigned int)arg1;
- (BOOL)isStartOfWordAtIndex:(unsigned int)arg1;
- (id)stringByTruncatingToLength:(unsigned int)arg1;
- (id)stringByEncryptingString;
- (id)stringByDecryptingString;
- (BOOL)FSRef:(struct FSRef *)arg1 createFileIfNecessary:(BOOL)arg2;
- (BOOL)FSSpec:(struct FSSpec *)arg1 createFileIfNecessary:(BOOL)arg2;
- (id)strictPathExtension;
- (id)strictStringByDeletingPathExtension;
- (id)stringByDeletingPercentEscapes;
@end

