//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableView.h"

@interface NSTableView (NSTableView_Extensions)
- (void)drawStripesInRect:(struct _NSRect)arg1 withColor:(id)arg2;
- (void)drawGridInClipRect:(struct _NSRect)arg1;
- (id)visibleSelectedRowIndexes;
@end

