//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@interface NSTextView (FindReplace)
- (struct _NSRange)findString:(id)arg1 options:(unsigned int)arg2 moreOptions:(int)arg3;
@end

