//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface NSView (NTExtensions)
- (float)verticalFraction;
- (void)setVerticalFraction:(float)arg1;
- (float)horizontalFraction;
- (void)setHorizontalFraction:(float)arg1;
- (void)drawFocusRing;
- (id)trackMouseDown:(id)arg1 dragSlop:(float)arg2;
- (BOOL)isDragEvent:(id)arg1 dragSlop:(float)arg2;
@end

