//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface NSWindow (Utilities)
+ (void)cascadeWindow:(id)arg1;
+ (BOOL)isAnyWindowVisibleWithDelegateClass:(Class)arg1;
+ (BOOL)isAnyWindowVisible;
+ (id)visibleWindows:(BOOL)arg1;
+ (id)miniaturizedWindows;
- (void)setFloating:(BOOL)arg1;
- (BOOL)isFloating;
@end

