//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTAppleDouble : NSObject
{
}

+ (BOOL)readAppleDoubleHeader:(int)arg1 outFileInfo:(struct FileInfo *)arg2 outResourceLength:(int *)arg3;
+ (BOOL)writeAppleDoubleHeader:(int)arg1 fileInfo:(struct FileInfo *)arg2 resourceLength:(int)arg3;

@end

