//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor, NSImage;

@interface NTBackgroundView : NSView
{
    int _drawingMode;
    NSImage *_backImage;
    NSColor *_backColor;
}

- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (BOOL)isOpaque;
- (void)setImageDrawingMode:(int)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)drawRect:(struct _NSRect)arg1;
- (BOOL)becomeFirstResponder;
- (void)setImage:(id)arg1;

@end

