//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTBoxView.h>

@interface NTBoxView (Private)
- (struct _NSRect)frameRect;
- (struct _NSRect)shadowRect;
- (void)drawShadow;
- (BOOL)windowIsMetallic;
- (id)frameColor;
- (id)shadowColor;
- (id)highlightColor;
- (id)lightHighlightColor;
@end

