//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@class NSString, NTPrefsBox, NTPrefsBoxMgr;

@interface NTCascadingWindow : NSWindow
{
    NTPrefsBoxMgr *_prefsBoxMgr;
    NTPrefsBox *_prefsBox;
    NSString *_autosaveName;
    struct _NSPoint _restoreFrameOrigin;
    BOOL _restoreWindowOriginOnly;
    BOOL _sentResizeMessage;
    BOOL _setPreferences;
    BOOL _performSelectorAfterDelay;
}

- (id)initWithContentRect:(struct _NSRect)arg1 styleMask:(unsigned int)arg2 backing:(int)arg3 defer:(BOOL)arg4;
- (void)dealloc;
- (void)windowMovedNotification:(id)arg1;
- (void)windowResizedNotification:(id)arg1;
- (void)setAutosaveName:(id)arg1;
- (id)autosaveName;
- (void)setRestoreWindowOriginOnly:(BOOL)arg1;
- (BOOL)setFrameUsingAutosaveName;
- (void)makeKeyAndOrderFront:(id)arg1;
- (void)orderWindow:(int)arg1 relativeTo:(int)arg2;
- (void)setWindowFramePref:(id)arg1;

@end

