//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTCascadingWindowHelper.h>

@interface NTCascadingWindowHelper (Private)
+ (struct _NSRect)nextWindowFrameFromStartingFrame:(struct _NSRect)arg1;
+ (id)screenForPoint:(struct _NSPoint)arg1;
+ (struct _NSRect)adjustWindowRect:(struct _NSRect)arg1 forScreenRect:(struct _NSRect)arg2;
+ (struct _NSRect)LargestRectAvoidingRect:(struct _NSRect)arg1 childRect:(struct _NSRect)arg2;
@end

