//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSEvent;

@interface NTClickState : NSObject
{
    BOOL _handled;
    int _renameOnMouseUpIndex;
    NSEvent *_event;
}

+ (id)clickState:(id)arg1;
- (id)initWithEvent:(id)arg1;
- (void)dealloc;
- (id)event;
- (BOOL)isHandled;
- (void)setHandled:(BOOL)arg1;
- (BOOL)isDoubleClick;
- (BOOL)isSingleClick;
- (BOOL)isRightClick;
- (BOOL)isLeftClick;
- (BOOL)isContextualMenuClick;
- (struct _NSPoint)mousePointForView:(id)arg1;
- (struct _NSPoint)mousePoint:(id)arg1;
- (BOOL)isShiftDown;
- (BOOL)isControlDown;
- (BOOL)isCommandDown;
- (BOOL)isOptionDown;
- (BOOL)tryRenameOnMouseUp;
- (void)setTryRenameOnMouseUpIndex:(int)arg1;
- (int)renameOnMouseUpIndex;

@end

