//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTColorMenu : NSObject
{
}

+ (id)sharedColors;
+ (id)colorMenuItem:(id)arg1 title:(id)arg2;
+ (id)colorMenu;
+ (id)colorForMenuItem:(id)arg1;

@end

