//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDateFormatter, NTRelativeDateFormatter;

@interface NTDateFormatter : NSObject
{
    NSDateFormatter *_shortFormatter;
    NSDateFormatter *_mediumFormatter;
    NSDateFormatter *_longFormatter;
    NTRelativeDateFormatter *_shortRelativeFormatter;
    NTRelativeDateFormatter *_mediumRelativeFormatter;
    NTRelativeDateFormatter *_longRelativeFormatter;
}

+ (void)initialize;
+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)dateString:(id)arg1 format:(int)arg2 relative:(BOOL)arg3;

@end

