//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTDateUtilities : NSObject
{
}

+ (id)dateFromUTCDateTime:(struct UTCDateTime)arg1;
+ (struct UTCDateTime)UTCDateTimeFromNSDate:(id)arg1;
+ (id)dateForJan1904;
+ (BOOL)UTCDateTimeIsEqualTo:(struct UTCDateTime)arg1 time:(struct UTCDateTime)arg2;

@end

