//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSLock, NSString;

@interface NTDate : NSObject
{
    NSDate *_date;
    NSLock *_threadLock;
    struct __stringFlags {
        unsigned int _longString_initialized:1;
        unsigned int _mediumString_initialized:1;
        unsigned int _shortString_initialized:1;
        unsigned int _longRelativeString_initialized:1;
        unsigned int _mediumRelativeString_initialized:1;
        unsigned int _shortRelativeString_initialized:1;
    } _stringFlags;
    NSString *_longString;
    NSString *_mediumString;
    NSString *_shortString;
    NSString *_longRelativeString;
    NSString *_mediumRelativeString;
    NSString *_shortRelativeString;
}

+ (id)dateWithDate:(id)arg1;
- (id)initWithDate:(id)arg1;
- (void)dealloc;
- (id)date;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)dateString:(int)arg1 relative:(BOOL)arg2;

@end

