//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage;

@interface NTDropBezel : NSObject
{
    NSImage *_borderImage;
}

- (void)dealloc;
- (void)drawInRect:(struct _NSRect)arg1 backColor:(id)arg2 flip:(BOOL)arg3;
- (struct _NSRect)drawingRectForBounds:(struct _NSRect)arg1;

@end

