//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PrefsBoxDelegate.h"

@class NSArray, NSButton, NSMatrix, NTPrefsBoxMgr;

@interface NTEncodingManager : NSObject <PrefsBoxDelegate>
{
    NSMatrix *encodingMatrix;
    NSButton *selectAllButton;
    NSButton *clearAllButton;
    NSButton *revertToDefaultButton;
    NSArray *encodings;
    NTPrefsBoxMgr *_prefsBoxMgr;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)enabledEncodings;
- (BOOL)worksWhenModal;
- (unsigned int)encodingForReading;
- (void)setEncodingForReading:(unsigned int)arg1;
- (unsigned int)encodingForWriting;
- (void)setEncodingForWriting:(unsigned int)arg1;
- (unsigned int)systemEncoding;
- (void)setupPopUp:(id)arg1 selectedEncoding:(unsigned int)arg2 withDefaultEntry:(BOOL)arg3;
- (void)prefsBoxModified:(id)arg1 forKey:(id)arg2;

@end

