//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTEncodingManager.h>

@interface NTEncodingManager (Actions)
- (void)showPanel:(id)arg1;
- (void)encodingListChanged:(id)arg1;
- (void)clearAll:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)revertToDefault:(id)arg1;
@end

