//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSButton, NTEncodingAccessoryView, NTEncodingPopUpButton;

@interface NTEncodingAccessoryController : NSObject
{
    id encodingText;
    NSButton *ignoreRTFCheck;
    NSButton *ignoreHTMLCheck;
    NTEncodingPopUpButton *encodingPopUpButton;
    NTEncodingAccessoryView *accessoryView;
    BOOL _reading;
    unsigned int _encoding;
    BOOL _ignoreRTF;
    BOOL _ignoreHTML;
}

- (id)initForReading:(BOOL)arg1 encoding:(unsigned int)arg2 ignoreRTF:(BOOL)arg3 ignoreHTML:(BOOL)arg4;
- (void)dealloc;
- (void)localizeStrings;
- (void)awakeFromNib;
- (id)accessoryView;
- (unsigned int)encoding;
- (BOOL)ignoreRTF;
- (BOOL)ignoreHTML;
- (void)ignoreRTFCheckAction:(id)arg1;
- (void)ignoreHTMLCheckAction:(id)arg1;
- (void)encodingPopUpAction:(id)arg1;

@end

