//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButton.h"

@interface NTEncodingPopUpButton : NSPopUpButton
{
    unsigned int defaultEncoding;
    BOOL hasDefaultEntry;
}

- (void)awakeFromNib;
- (void)setEncoding:(unsigned int)arg1 defaultEntry:(BOOL)arg2;
- (void)dealloc;
- (void)encodingsListChanged:(id)arg1;

@end

