//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface NTEncodingAccessoryView : NSView
{
    id _controller;
}

+ (id)accessoryViewForReading:(unsigned int)arg1 ignoreRTF:(BOOL)arg2 ignoreHTML:(BOOL)arg3;
+ (id)accessoryViewForWriting:(unsigned int)arg1;
- (void)setController:(id)arg1;
- (void)dealloc;
- (unsigned int)encoding;
- (BOOL)ignoreRTF;
- (BOOL)ignoreHTML;

@end

