//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTEncodingManager.h>

@interface NTEncodingManager (Private)
+ (id)allAvailableStringEncodings;
- (id)prefsBox;
- (id)prefsBoxWithName:(id)arg1;
- (void)setupEncodingsList;
- (void)noteEncodingListChange:(BOOL)arg1 updateList:(BOOL)arg2 postNotification:(BOOL)arg3;
@end

