//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSDictionary, NSString, NTGlyphBlitter;

@interface NTFastTextView : NSView
{
    NTGlyphBlitter *_blitter;
    NSString *_textString;
    NSDictionary *_attributes;
    SEL _action;
    id _target;
}

+ (id)fastTextView:(id)arg1 action:(SEL)arg2 target:(id)arg3 attributes:(id)arg4;
- (id)initWithString:(id)arg1 action:(SEL)arg2 target:(id)arg3 attributes:(id)arg4;
- (void)dealloc;
- (void)mouseDown:(id)arg1;
- (BOOL)isFlipped;
- (struct _NSSize)sizeForBounds:(struct _NSRect)arg1;
- (void)drawRect:(struct _NSRect)arg1;
- (id)blitterForSize:(struct _NSSize)arg1;

@end

