//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTFirstResponderMessenger : NSObject
{
    id _param;
}

+ (id)messenger;
- (id)init;
- (void)dealloc;
- (void)send:(SEL)arg1 with:(id)arg2;
- (BOOL)sendToTopWindow:(SEL)arg1 with:(id)arg2;
- (id)param;

@end

