//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NTFont;

@interface NTFontButton : NSButton
{
    id delegate;
    NTFont *_displayedFont;
}

- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (void)setDisplayedFont:(id)arg1;
- (id)displayedFont;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)setFontUsingFontPanel:(id)arg1;
- (void)changeFont:(id)arg1;
- (void)drawRect:(struct _NSRect)arg1;
- (BOOL)isFlipped;
- (BOOL)acceptsFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;

@end

