//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFont;

@interface NTFont : NSObject
{
    NSFont *normal;
    NSFont *bold;
    NSFont *italic;
    NSFont *boldItalic;
}

+ (id)fontWithFont:(id)arg1;
- (id)initWithFont:(id)arg1;
- (void)dealloc;
- (id)normal;
- (id)bold;
- (id)italic;
- (id)boldItalic;
- (id)displayString;

@end

