//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface NTFramedView : NSView
{
    int _edgesToFrame;
}

- (id)initWithFrame:(struct _NSRect)arg1 edges:(int)arg2;
- (void)dealloc;
- (struct _NSRect)contentBounds;
- (void)drawRect:(struct _NSRect)arg1;

@end

