//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTGlyphSegment.h>

@interface NTGlyphSegment (Private)
- (id)backgroundPath:(struct _NSRect)arg1 ovalBackground:(BOOL)arg2;
- (BOOL)drawBackColor:(id)arg1 frame:(struct _NSRect)arg2 ovalBackground:(BOOL)arg3;
- (void)applyTextColor:(id)arg1;
- (void)applyFont;
- (id)backgroundBezierPathForRect:(struct _NSRect)arg1;
@end

