//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTGlyphBlitter.h>

@interface NTGlyphBlitter (Private)
+ (id)buildSegments:(id)arg1 outMinRect:(struct _NSRect *)arg2 size:(struct _NSSize)arg3 drawLines:(int)arg4 backColor:(id)arg5 antialias:(BOOL)arg6 shadowText:(BOOL)arg7;
- (struct _NSRect)drawRectForRect:(struct _NSRect)arg1;
@end

