//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor, NSDictionary;

@interface NTGlyphSegment : NSObject
{
    int _numGlyphs;
    unsigned short *_glyphs;
    struct CGSize *_advances;
    struct _NSPoint *_glyphLocations;
    struct _NSRect _lineRect;
    struct _NSRange _textRange;
    NSDictionary *_attributes;
    NSColor *_backColor;
    BOOL _shadow;
    BOOL _antialias;
}

+ (id)segmentWithLayoutManager:(id)arg1 lineRect:(struct _NSRect)arg2 range:(struct _NSRange)arg3 attributes:(id)arg4 backColor:(id)arg5 antialias:(BOOL)arg6 shadow:(BOOL)arg7;
- (id)initWithRange:(struct _NSRange)arg1 lineRect:(struct _NSRect)arg2 numGlyphs:(int)arg3 glyphs:(const unsigned short *)arg4 locations:(const struct _NSPoint *)arg5 advances:(const struct CGSize *)arg6 attributes:(id)arg7 backColor:(id)arg8 antialias:(BOOL)arg9 shadow:(BOOL)arg10;
- (void)dealloc;
- (void)drawRect:(struct _NSRect)arg1 textColor:(id)arg2;

@end

