//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTGradientFill.h>

@interface NTGradientFill (Private)
- (void)setColor:(id)arg1;
- (struct CGFunction *)createFunction;
- (void)drawGradientInRect:(struct _NSRect)arg1;
- (void)modifyColorBeforeShading;
@end

