//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor;

@interface NTGradientFill : NSObject
{
    struct CGColorSpace *_colorSpace;
    struct CGShading *_shading;
    struct CGFunction *_function;
    struct CGPoint _startPoint;
    struct CGPoint _endPoint;
    NSColor *_color;
    int _numComponents;
    float _colorArray[4];
    BOOL _flip;
    float _amountChange;
}

- (id)initWithType:(int)arg1 flip:(BOOL)arg2;
- (id)init;
- (void)dealloc;
- (void)fillRect:(struct _NSRect)arg1 withColor:(id)arg2;
- (void)fillBezierPath:(id)arg1 withColor:(id)arg2;

@end

