//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTHeaderControlCell.h>

@interface NTHeaderControlCell (Private)
- (id)attributes;
- (id)glyphBlitter:(id)arg1 size:(struct _NSSize)arg2;
@end

