//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTID3;

@interface NTID3Helper : NSObject
{
    NTID3 *_id3;
}

+ (id)helperWithPath:(id)arg1;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (id)infoString;
- (id)image;

@end

