//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTImageConverter : NSObject
{
}

+ (id)sharedInstance;
- (id)convertImage:(id)arg1 format:(int)arg2 compression:(float)arg3;

@end

