//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTKeyChainUtils : NSObject
{
}

+ (id)passwordForService:(id)arg1 accountName:(id)arg2;
+ (void)dumpKeyChainData;

@end

