//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTLoginItemMgr : NSObject
{
}

+ (BOOL)isLoginItem:(id)arg1;
+ (int)loginIndex:(id)arg1;
+ (void)removeLoginItem:(id)arg1;
+ (void)addLoginItem:(id)arg1 hide:(BOOL)arg2;
+ (void)reorderLoginItemToEnd:(id)arg1 hide:(BOOL)arg2;

@end

