//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSMovieView;

@interface NTMovieView : NSView
{
    NSMovieView *_movieView;
    float _sizeRatio;
}

- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (void)drawRect:(struct _NSRect)arg1;
- (BOOL)isOpaque;
- (BOOL)acceptsFirstMouse;
- (void)setMovie:(id)arg1;
- (id)movie;
- (void *)movieController;
- (void)start:(id)arg1;
- (void)stop:(id)arg1;
- (BOOL)isPlaying;
- (void)showController:(BOOL)arg1 adjustingSize:(BOOL)arg2;
- (BOOL)isControllerVisible;
- (void)setLoopMode:(int)arg1;
- (int)loopMode;

@end

