//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTRectArray.h>

@interface NTMutableRectArray : NTRectArray
{
}

- (void)addRect:(struct _NSRect)arg1;
- (void)removeRectAtIndex:(int)arg1;
- (void)removeRectsIntersectingRect:(struct _NSRect)arg1;

@end

