//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface NTNoRetainArray : NSObject
{
    NSMutableArray *_array;
}

- (id)init;
- (void)dealloc;
- (void)addObject:(id)arg1;
- (void)removeObject:(id)arg1;
- (int)count;
- (id)objectAtIndex:(int)arg1;

@end

