//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface NTPath : NSObject
{
    NSString *_path;
    char *_fileSystemPath;
    char *_UTF8Path;
}

+ (id)pathWithPath:(id)arg1;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (id)path;
- (id)parentPath;
- (const char *)fileSystemPath;
- (const char *)UTF8Path;

@end

