//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCell.h"

@class NSString, NSTableHeaderCell, NTGlyphBlitter;

@interface NTPopUpHeaderViewCell : NSCell
{
    NSTableHeaderCell *_tableHeaderCell;
    NTGlyphBlitter *_glyphBlitter;
    NSString *_drawnTitle;
}

- (void)commonInit;
- (id)init;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)drawInteriorWithFrame:(struct _NSRect)arg1 inView:(id)arg2;
- (struct _NSSize)cellSizeForBounds:(struct _NSRect)arg1;
- (struct _NSRect)drawingRectForBounds:(struct _NSRect)arg1;
- (BOOL)trackMouse:(id)arg1 inRect:(struct _NSRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;

@end

