//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButton.h"

@class NSImageView;

@interface NTPopUpButton : NSPopUpButton
{
    NSImageView *_imageView;
}

- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (void)setImage:(id)arg1;
- (void)drawRect:(struct _NSRect)arg1;

@end

