//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSControl.h"

@interface NTPopUpHeaderView : NSControl
{
}

+ (Class)cellClass;
+ (id)viewWithFrame:(struct _NSRect)arg1 title:(id)arg2;
+ (float)defaultHeight;
- (id)initWithFrame:(struct _NSRect)arg1;
- (BOOL)isFlipped;
- (void)setMenu:(id)arg1;
- (void)setTitle:(id)arg1;

@end

