//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSMutableDictionary, NSString;

@interface NTPrefsBox : NSObject <NSCopying, NSCoding>
{
    NSString *_name;
    NSMutableDictionary *_dictionary;
    id _delegate;
}

- (id)initWithName:(id)arg1;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (id)name;
- (id)dictionaryForKey:(id)arg1 defaultValue:(id)arg2;
- (int)intForKey:(id)arg1 defaultValue:(int)arg2;
- (unsigned int)unsignedIntForKey:(id)arg1 defaultValue:(unsigned int)arg2;
- (float)floatForKey:(id)arg1 defaultValue:(float)arg2;
- (double)doubleForKey:(id)arg1 defaultValue:(double)arg2;
- (id)stringForKey:(id)arg1 defaultValue:(id)arg2;
- (BOOL)boolForKey:(id)arg1 defaultValue:(BOOL)arg2;
- (id)arrayForKey:(id)arg1 defaultValue:(id)arg2;
- (id)numberForKey:(id)arg1 defaultValue:(id)arg2;
- (struct _NSRect)rectForKey:(id)arg1 defaultValue:(struct _NSRect)arg2;
- (id)fontForKey:(id)arg1 defaultValue:(id)arg2;
- (id)colorForKey:(id)arg1 defaultValue:(id)arg2;
- (void)setDictionary:(id)arg1 forKey:(id)arg2;
- (void)setInt:(int)arg1 forKey:(id)arg2;
- (void)setUnsignedInt:(unsigned int)arg1 forKey:(id)arg2;
- (void)setFloat:(float)arg1 forKey:(id)arg2;
- (void)setDouble:(double)arg1 forKey:(id)arg2;
- (void)setString:(id)arg1 forKey:(id)arg2;
- (void)setBool:(BOOL)arg1 forKey:(id)arg2;
- (void)setArray:(id)arg1 forKey:(id)arg2;
- (void)setNumber:(id)arg1 forKey:(id)arg2;
- (void)setRect:(struct _NSRect)arg1 forKey:(id)arg2;
- (void)setFont:(id)arg1 forKey:(id)arg2;
- (void)setColor:(id)arg1 forKey:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

