//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableSet;

@interface NTPrefNotification : NSObject
{
    id _sender;
    NSMutableSet *_set;
}

+ (id)notification:(id)arg1;
+ (id)notification:(id)arg1 withPreference:(id)arg2;
+ (id)notification:(id)arg1 withPreferences:(id)arg2;
+ (id)extractFromNotification:(id)arg1;
- (id)initWithSender:(id)arg1;
- (void)dealloc;
- (void)setSender:(id)arg1;
- (id)sender;
- (void)sendNotification;
- (void)sendNotificationWithDocument:(id)arg1;
- (BOOL)isPreferenceChanged:(id)arg1;
- (BOOL)isAnyPreferenceChanged:(id)arg1;
- (void)addPreference:(id)arg1;
- (void)addPreferences:(id)arg1;
- (int)numPreferences;

@end

