//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NTProgressBar;

@interface NTProgressPanelController : NSWindowController
{
    id progressBar;
    id progressText;
    id infoText;
    id stopButton;
    BOOL _stopButtonClicked;
    NTProgressBar *_progressBar;
}

- (id)initWithWindowTitle:(id)arg1;
- (id)initWithProgressBar:(id)arg1 windowTitle:(id)arg2 stoppable:(BOOL)arg3;
- (void)dealloc;
- (void)awakeFromNib;
- (void)updateProgress:(id)arg1 message:(id)arg2 info:(id)arg3;
- (void)stopAction:(id)arg1;
- (void)setIndeterminate:(BOOL)arg1;
- (BOOL)stoppedByUser;
- (void)setWindowTitle:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)showWindow:(id)arg1;

@end

