//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PrefsBoxDelegate.h"

@class NSMutableDictionary;

@interface NTPrefsBoxMgr : NSObject <PrefsBoxDelegate>
{
    NSMutableDictionary *_prefBoxes;
    id _delegate;
}

- (id)init;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (id)prefsBoxMgrState;
- (void)setPrefsBoxMgrState:(id)arg1;
- (id)prefsBoxWithName:(id)arg1;
- (void)prefsBoxModified:(id)arg1 forKey:(id)arg2;

@end

