//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTPrefsBox.h>

@interface NTPrefsBox (Private)
+ (id)prefsBoxFromPrefsFileWithName:(id)arg1;
+ (void)setPrefBox:(id)arg1 toPrefsFileWithName:(id)arg2;
- (id)valueForKey:(id)arg1 defaultValue:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setValue:(id)arg1 forKey:(id)arg2 synchronize:(BOOL)arg3;
- (void)synchronizeValue:(id)arg1 forKey:(id)arg2;
@end

