//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTProgressBar.h>

@interface NTProgressBar (Private)
- (id)initWithTitle:(id)arg1 indeterminate:(BOOL)arg2 stoppable:(BOOL)arg3;
- (BOOL)isIndeterminate;
- (BOOL)finished;
- (BOOL)needsUpdate;
- (void)setNeedsUpdate:(BOOL)arg1;
- (id)progressController;
- (void)createProgressController;
- (BOOL)needsIndeterminateUpdate;
- (void)setNeedsIndeterminateUpdate:(BOOL)arg1;
- (BOOL)needsTitleUpdate;
- (void)setNeedsTitleUpdate:(BOOL)arg1;
- (id)windowTitle;
- (id)percentage;
- (id)infoMessage;
- (id)progressMessage;
@end

