//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTPromptForStringPanelController.h>

@interface NTPromptForStringPanelController (Private)
- (void)handleResult:(int)arg1;
- (void)localizeInterface;
- (void)replaceEditFieldForSecurity;
- (void)OKAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)sheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
@end

