//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTRawString : NSObject
{
    unsigned int _length;
    unsigned short *_buffer;
}

+ (id)rawString:(id)arg1;
- (id)initWithString:(id)arg1;
- (void)dealloc;
- (unsigned int)length;
- (unsigned short *)buffer;

@end

