//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@interface NTRectArray : NSObject <NSCopying, NSMutableCopying>
{
    int _numRects;
    struct _NSRect *_rects;
    int _arrayCapacity;
    struct _NSRect _bounds;
}

- (id)init;
- (id)initWithRect:(struct _NSRect)arg1;
- (void)dealloc;
- (unsigned int)count;
- (struct _NSRect)rectAtIndex:(int)arg1;
- (struct _NSRect)bounds;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (BOOL)intersectsPoint:(struct _NSPoint)arg1;
- (BOOL)intersectsRect:(struct _NSRect)arg1;
- (struct _NSRect)intersection:(struct _NSRect)arg1;
- (struct _NSRect)bestIntersection:(struct _NSRect)arg1;

@end

