//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTMutableRectArray;

@interface NTRectSlicer : NSObject
{
    struct _NSRect _rect;
    struct _NSSize _itemSize;
    NTMutableRectArray *_slices;
}

+ (id)slicedRect:(struct _NSRect)arg1 withSize:(struct _NSSize)arg2;
- (id)initWithRect:(struct _NSRect)arg1 itemSize:(struct _NSSize)arg2;
- (void)dealloc;
- (struct _NSRect)rect;
- (struct _NSSize)itemSize;
- (id)rectSlices;

@end

