//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@class NTGlyphBlitter;

@interface NTSelectableButtonCell : NSButtonCell
{
    NTGlyphBlitter *_textBlitter;
}

- (void)commonInit;
- (id)init;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)drawInteriorWithFrame:(struct _NSRect)arg1 inView:(id)arg2;
- (void)doDrawInteriorWithFrame:(struct _NSRect)arg1 inView:(id)arg2 textColor:(id)arg3 backColor:(id)arg4;
- (void)drawWithFrame:(struct _NSRect)arg1 inView:(id)arg2;
- (void)highlight:(BOOL)arg1 withFrame:(struct _NSRect)arg2 inView:(id)arg3;
- (void)highlightColors:(id *)arg1 highlightBackColor:(id *)arg2 controlView:(id)arg3;

@end

