//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTSendMail.h>

@interface NTSendMail (Private)
+ (void)doSendEmailTo:(id)arg1 subject:(id)arg2 attrString:(id)arg3;
@end

