//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTSendMail : NSObject
{
}

+ (void)sendEmailTo:(id)arg1 subject:(id)arg2 textAttachment:(id)arg3 attachName:(id)arg4;
+ (void)sendEmailTo:(id)arg1 subject:(id)arg2 fileAttachment:(id)arg3;
+ (void)sendEmailUsingMailTo:(id)arg1 subject:(id)arg2 fileAttachments:(id)arg3;

@end

