//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NTSharedImage;

@interface NTSharedImageContainer : NSObject
{
    NTSharedImage *_image;
}

+ (id)imageContainer:(id)arg1;
- (id)initWithImage:(id)arg1;
- (id)image;

@end

