//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTSimpleOKCancelPanel : NSObject
{
    SEL _selector;
    id _target;
    id _contextInfo;
    int _resultCode;
}

+ (void)runPanel:(id)arg1 selector:(SEL)arg2 title:(id)arg3 message:(id)arg4 context:(id)arg5 window:(id)arg6;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 contextInfo:(id)arg3;
- (void)dealloc;
- (void)start:(id)arg1 message:(id)arg2 window:(id)arg3;
- (void)sheetDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (id)contextInfo;
- (int)resultCode;

@end

