//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface NTSimpleButton : NSButton
{
}

+ (struct _NSSize)preferredSize;
+ (id)cellClass;
- (id)initWithFrame:(struct _NSRect)arg1 type:(int)arg2 toggleButton:(BOOL)arg3;
- (void)dealloc;

@end

