//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTSimpleButton.h>

@interface NTSimpleButton (Private)
- (id)contentPathForRect:(struct _NSRect)arg1 type:(int)arg2;
- (id)radioOffImage:(int)arg1;
- (id)radioOnImage:(int)arg1;
- (id)stopImage;
- (id)altStopImage;
- (id)makeStopImage:(id)arg1;
- (void)setupStopButton;
- (id)createRadioOffImage:(int)arg1;
- (id)createRadioOnImage:(int)arg1;
@end

