//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@interface NTSimpleButtonCell : NSButtonCell
{
}

- (void)commonInit;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)highlight:(BOOL)arg1 withFrame:(struct _NSRect)arg2 inView:(id)arg3;
- (BOOL)startTrackingAt:(struct _NSPoint)arg1 inView:(id)arg2;
- (BOOL)continueTracking:(struct _NSPoint)arg1 at:(struct _NSPoint)arg2 inView:(id)arg3;
- (void)stopTracking:(struct _NSPoint)arg1 at:(struct _NSPoint)arg2 inView:(id)arg3 mouseIsUp:(BOOL)arg4;
- (BOOL)trackMouse:(id)arg1 inRect:(struct _NSRect)arg2 ofView:(id)arg3 untilMouseUp:(BOOL)arg4;

@end

