//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface NTSimpleAlert : NSObject
{
}

+ (void)alertSheet:(id)arg1 message:(id)arg2 subMessage:(id)arg3;
+ (void)criticalAlertSheet:(id)arg1 message:(id)arg2 subMessage:(id)arg3;
+ (void)infoSheet:(id)arg1 message:(id)arg2 subMessage:(id)arg3;
+ (void)alertPanel:(id)arg1 subMessage:(id)arg2;
+ (void)criticalAlertPanel:(id)arg1 subMessage:(id)arg2;
+ (void)infoPanel:(id)arg1 subMessage:(id)arg2;

@end

