//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NTSimpleTimerProtocol.h"

@class NTSimpleTimer;

@interface NTSoundPlayer : NSObject <NTSimpleTimerProtocol>
{
    struct SndChannel *_soundChannel;
    struct SndListResource **_soundHandle;
    CDUnknownFunctionPointerType _soundCallBackUPP;
    NTSimpleTimer *_deleteTimer;
    BOOL _setSoundFinishedPlaying;
}

+ (void)playSound:(struct SndListResource **)arg1;
- (id)init;
- (void)dealloc;
- (void)delegate_simpleTimerNotification:(id)arg1;

@end

