//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface NTSpringLoadedHelper : NSObject
{
    NSDate *_springLoadedStartTime;
    struct _NSRect _springLoadedMouseRect;
}

- (void)dealloc;
- (int)performSpringLoadedStageForTime;
- (void)start;
- (void)end;
- (void)recordSpringLoadedMousePosition;
- (BOOL)isSpringLoadedMousePositionValid;

@end

