//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTSRMOutputParser.h>

@interface NTSRMOutputParser (Private)
- (id)extractPathLines:(id)arg1;
@end

