//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor, NSDictionary, NTGlyphBlitter, NTStringDelegate;

@interface NTStringImager : NSObject
{
    NTStringDelegate *_delegate;
    NTGlyphBlitter *_glyphBlitter;
    NSDictionary *_attributes;
    NSColor *_highlightTextColor;
    NSColor *_highlightBackColor;
    NSColor *_labelColor;
    BOOL _ovalBackground;
    BOOL _antiAlias;
    BOOL _shadowText;
    BOOL _blackText;
    BOOL _verticallyCenter;
    int _numLines;
    int _alignment;
}

+ (id)imageWithDelegate:(id)arg1 attributes:(id)arg2 highlightTextColor:(id)arg3 highlightBackColor:(id)arg4 labelColor:(id)arg5 ovalBackground:(BOOL)arg6 antiAlias:(BOOL)arg7 shadowText:(BOOL)arg8 blackText:(BOOL)arg9 verticallyCenter:(BOOL)arg10 numLines:(int)arg11 alignment:(int)arg12;
- (id)initWithDelegate:(id)arg1 attributes:(id)arg2 highlightTextColor:(id)arg3 highlightBackColor:(id)arg4 labelColor:(id)arg5 ovalBackground:(BOOL)arg6 antiAlias:(BOOL)arg7 shadowText:(BOOL)arg8 blackText:(BOOL)arg9 verticallyCenter:(BOOL)arg10 numLines:(int)arg11 alignment:(int)arg12;
- (void)dealloc;
- (struct _NSRect)textRectForRect:(struct _NSRect)arg1;
- (void)drawInView:(id)arg1 rect:(struct _NSRect)arg2 highlight:(BOOL)arg3 drawTextOnly:(BOOL)arg4;
- (void)drawInView:(id)arg1 rect:(struct _NSRect)arg2 highlight:(BOOL)arg3;
- (void)resetIfDifferent:(id)arg1 highlightBackColor:(id)arg2 labelColor:(id)arg3 antiAlias:(BOOL)arg4 shadowText:(BOOL)arg5 blackText:(BOOL)arg6 verticallyCenter:(BOOL)arg7 alignment:(int)arg8;

@end

