//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTSUTaskController : NSObject
{
    id _delegate;
    BOOL _sendOutput;
    BOOL _sendError;
    BOOL _sendFinished;
}

+ (BOOL)synchronousTask:(id)arg1 toolPath:(id)arg2 withArgs:(id)arg3;
+ (BOOL)asynchronousTask:(id)arg1 withArgs:(id)arg2;
- (id)initWithDelegate:(id)arg1;
- (void)dealloc;
- (BOOL)runTask:(BOOL)arg1 toolPath:(id)arg2 withArgs:(id)arg3;

@end

