//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface NTTaskOutputParser : NSObject
{
    NSString *_leftOverText;
    NSMutableArray *_taskOutput;
}

- (id)init;
- (void)dealloc;
- (unsigned int)numPaths;
- (id)lastPath;
- (void)addOutput:(id)arg1;

@end

