//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface NTTextAttributeMgr : NSObject
{
    NSDictionary *_normalAttributes;
    NSDictionary *_boldAttributes;
    NSDictionary *_boldItalicAttributes;
    NSDictionary *_italicAttributes;
    int _alignment;
}

- (id)init;
- (id)initWithFont:(id)arg1 color:(id)arg2 alignment:(int)arg3;
- (void)dealloc;
- (id)attributesForStyle:(int)arg1 alignment:(int)arg2;

@end

