//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTextStorage;

@interface NTTextBox : NSObject
{
    NSTextStorage *_contents;
}

- (id)init;
- (void)dealloc;
- (void)setContents:(id)arg1;
- (id)contents;
- (struct _NSRect)drawRect:(struct _NSRect)arg1 backColor:(id)arg2;
- (struct _NSSize)requiredSizeForRect:(struct _NSRect)arg1;

@end

