//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTTextSummary : NSObject
{
    struct OpaqueFBCSummaryRef *_summaryRef;
}

- (id)initWithString:(id)arg1;
- (void)dealloc;
- (id)summary:(int)arg1 paragraphs:(BOOL)arg2;
- (unsigned int)numSentences;

@end

