//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSLock, NSMutableArray;

@interface NTThreadSafeNotificationMgr : NSObject
{
    NSMutableArray *_threadSafeNotifications;
    NSLock *_threadLock;
    BOOL _tickleMessageSent;
    NSArray *_modes;
    NSLock *_nameLock;
    int _uniqueNameCount;
}

+ (id)sharedInstance;
- (id)init;
- (void)dealloc;
- (id)uniqueName;
- (void)addThreadSafeNotification:(id)arg1 withName:(id)arg2;

@end

