//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSLock;

@interface NTThreadWorker : NSObject
{
    BOOL _halt;
    BOOL _idle;
    id _notificationName;
    NSLock *_threadLock;
}

- (id)initWithNotificationName:(id)arg1;
- (void)dealloc;
- (BOOL)halt;
- (void)setHalt;
- (BOOL)idle;
- (void)setIdle:(BOOL)arg1;
- (void)runThread:(id)arg1;
- (void)workerMethod:(id)arg1;
- (BOOL)doWorkerMethod:(id)arg1;
- (void)notifyThreadOutput:(id)arg1;

@end

