//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NTThreadWorker;

@interface NTThreadWorkerController : NSObject
{
    NTThreadWorker *_thread;
    NSString *_notificationName;
}

- (id)init;
- (void)stopThread;
- (void)halt;
- (id)notificationName;
- (void)dealloc;
- (void)runThread:(Class)arg1 param:(id)arg2;
- (BOOL)idle;

@end

