//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class NSString;

@interface NTTitledInfoPair : NSObject
{
    NSString *_title;
    NSString *_info;
    SEL _action;
    id _target;
}

+ (id)infoPair:(id)arg1 info:(id)arg2;
+ (id)infoPair:(id)arg1 info:(id)arg2 action:(SEL)arg3 target:(id)arg4;
- (id)initWithTitle:(id)arg1 info:(id)arg2 action:(SEL)arg3 target:(id)arg4;
- (void)dealloc;
- (id)title;
- (id)info;
- (SEL)action;
- (id)target;

@end

