//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSMutableArray;

@interface NTTitledInfoView : NSView
{
    id _target;
    NSMutableArray *_pairs;
    NSMutableArray *_titleViews;
    NSMutableArray *_infoViews;
    int _titleWidth;
    int _horizontalOffset;
    int _verticalOffset;
    BOOL _inFrameChanged;
    NSMutableArray *_backgroundLineOffsets;
    int _backgroundShadowOffset;
}

- (id)initWithFrame:(struct _NSRect)arg1;
- (void)dealloc;
- (void)setTarget:(id)arg1;
- (BOOL)isFlipped;
- (void)setHorizontalOffset:(int)arg1;
- (void)setVerticalOffset:(int)arg1;
- (void)setWithArray:(id)arg1;
- (void)drawRect:(struct _NSRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct _NSSize)arg1;

@end

