//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTTitledInfoView.h>

@interface NTTitledInfoView (Private)
- (void)doDrawRect:(struct _NSRect)arg1;
- (void)resizeFrameToFit;
- (void)reset;
- (void)createViews;
- (void)positionViews;
- (int)totalHeight;
- (void)resetBackgroundLineOffsets;
- (void)resetBackgroundShadowOffset;
- (id)titleShadowColor;
- (id)infoLineColor;
- (void)drawBackgroundShadow;
- (void)drawBackgroundLines;
- (id)titleAttributes;
- (id)infoAttributes;
@end

