//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSString;

@interface NTToolbarItemDesc : NSObject
{
    NSString *identifier;
    NSString *name;
    NSImage *icon;
    SEL selector;
    BOOL _nilTarget;
}

- (id)initWithIdentifier:(id)arg1 name:(id)arg2 icon:(id)arg3 selector:(SEL)arg4 nilTarget:(BOOL)arg5;
- (void)dealloc;
- (id)identifier;
- (id)name;
- (id)icon;
- (SEL)selector;
- (BOOL)nilTarget;

@end

