//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSToolbarItem;

@interface NTToolbarItemSpec : NSObject
{
    BOOL _nilTarget;
    NSToolbarItem *_item;
}

+ (id)itemWithItem:(id)arg1 nilTarget:(BOOL)arg2;
- (id)initWithItem:(id)arg1 nilTarget:(BOOL)arg2;
- (void)dealloc;
- (id)item;
- (BOOL)nilTarget;
- (int)compareByName:(id)arg1;

@end

