//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSView;

@interface NTToolTipManager : NSObject
{
    NSView *_view;
    NSMutableArray *_toolTips;
}

- (id)initWithView:(id)arg1;
- (void)dealloc;
- (void)addToolTipRect:(struct _NSRect)arg1 forIndex:(unsigned int)arg2;
- (void)setNumItems:(unsigned int)arg1;

@end

