//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTToolTip : NSObject
{
    BOOL _isValid;
    int _tag;
    struct _NSRect _rect;
}

+ (id)invalidToolTip;
+ (id)toolTip:(struct _NSRect)arg1 tag:(int)arg2;
- (id)init;
- (id)initWithRect:(struct _NSRect)arg1 tag:(int)arg2;
- (void)dealloc;
- (BOOL)isValid;
- (struct _NSRect)rect;
- (int)tag;

@end

