//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSWindow;

@interface NTTransparencySheetController : NSObject
{
    id transparencySlider;
    id window;
    id _target;
    SEL _selector;
    NSWindow *_parentWindow;
}

+ (void)target:(id)arg1 selector:(SEL)arg2 parentWindow:(id)arg3;
- (id)initWithTarget:(id)arg1 selector:(SEL)arg2 parentWindow:(id)arg3;
- (void)awakeFromNib;
- (void)run;
- (void)dealloc;
- (float)transparency;
- (void)transparencySliderAction:(id)arg1;
- (void)closeButtonAction:(id)arg1;

@end

