//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CocoaTechBase/NTZoomScrollView.h>

@interface NTZoomScrollView (Private)
- (id)prefsBox;
- (int)scaleValueFromMenuItem:(id)arg1;
- (void)selectScaleValueInPopup:(int)arg1;
- (void)setScaleValue:(int)arg1 adjustPopup:(BOOL)arg2 saveAsDefault:(BOOL)arg3;
- (void)makeScalePopUpButton;
- (void)tile;
- (void)scalePopUpAction:(id)arg1;
- (void)setHasHorizontalScroller:(BOOL)arg1;
@end

