//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NTID3 : NSObject
{
    void *_tag;
}

+ (id)id3WithPath:(id)arg1;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (id)title;
- (id)artist;
- (id)album;
- (id)comments;
- (id)copyright;
- (id)track;
- (id)genre;
- (id)year;
- (id)bitRate;
- (id)sampleRate;
- (id)duration;
- (id)channels;
- (id)format;
- (id)image;

@end

